# ndarray

In [151]:
import numpy as np

: 

## ndarray declaration 

### 1d array

In [152]:
arr1d = np.array([1, 2, 3, 4, 5])
print(type(arr1d), arr1d)
print(arr1d.ndim)
print(arr1d.shape)
print(arr1d.dtype)
print(arr1d.size)

<class 'numpy.ndarray'> [1 2 3 4 5]
1
(5,)
int64
5


: 

### 2d array

In [153]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.dtype)
print(arr2d.size)

2
(2, 3)
int64
6


: 

### 3d array

In [154]:
arr3d = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11, 12]]])
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.dtype)
print(arr3d.size)

3
(2, 2, 3)
int64
12


: 

## data type

### upcasting to float

In [155]:
floatArr = np.array([1, 2, 3.5])
print(floatArr.dtype)

float64


: 

### upcasting to string

In [156]:
stringArr = np.array([1, 2, "3"])
print(stringArr.dtype)

<U21


: 

### selecting a data type for an array

In [157]:
arrInt8 = np.array([1, 2, 3], dtype=np.int8)
print(arrInt8.dtype)

int8


: 

### changing data type of an exisitng arr

In [159]:
arrFloat16 = arrInt8.astype(np.float16)
print(arrFloat16.dtype, arrFloat16)

float16 [1. 2. 3.]


: 

## nd array creation from existing data

### list

In [160]:
lst = [1, 2, 3.5]
arrLst = np.array(lst)
print(type(arrLst))
print(arrLst.dtype)


<class 'numpy.ndarray'>
float64


: 

### tuple

In [161]:
tup = (1, 2, 3)
arrTup = np.array(tup)
print(type(arrTup), arrTup)
print(arrTup.dtype)
print(arrTup.shape)
print(arrTup.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1


: 

### set

In [162]:
_set = {1, 2, 3}    
arrSet = np.array(_set)    # treats the whole set as one single element
print(type(arrSet), arrSet)
print(arrSet.dtype)
print(arrSet.shape)
print(arrSet.ndim)

<class 'numpy.ndarray'> {1, 2, 3}
object
()
0


: 

In [163]:
arrSet = np.array(list(_set))    # thus, the set has to be typecasted to a list first
print(type(arrSet), arrSet)
print(arrSet.dtype)
print(arrSet.shape)
print(arrSet.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1


: 

### dictionary

In [164]:
dic = {"a" : 1, "b" : 2, "c" : 3}
items = dic.items()
print(f"items: {items}")

keys = dic.keys()
print(f"keys: {keys}")

values = dic.values()
print(f"values: {values}")

items: dict_items([('a', 1), ('b', 2), ('c', 3)])
keys: dict_keys(['a', 'b', 'c'])
values: dict_values([1, 2, 3])


: 

In [165]:
arrKeys = np.array(list(keys))    # treats the list within the tuple as one single element. thus, the tuple has to be typecasted to a list first
print(type(arrKeys), arrKeys)
print(arrKeys.dtype)
print(arrKeys.shape)
print(arrKeys.ndim)

<class 'numpy.ndarray'> ['a' 'b' 'c']
<U1
(3,)
1


: 

In [166]:
arrValues = np.array(list(values))    # treats the list within the tuple as one single element. thus, the tuple has to be typecasted to a list first
print(type(arrValues), arrValues)
print(arrValues.dtype)
print(arrValues.shape)
print(arrValues.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1


: 

In [167]:
arrItems = np.array(items)
print(type(arrItems), arrItems)
print(arrItems.dtype)
print(arrItems.shape)
print(arrItems.ndim)

<class 'numpy.ndarray'> dict_items([('a', 1), ('b', 2), ('c', 3)])
object
()
0


: 

### creating ndarray from scratch

#### zeros()

In [168]:
arrScratch = np.zeros((2, 3))
print(type(arrScratch), arrScratch)
print(arrScratch.dtype)
print(arrScratch.shape)
print(arrScratch.ndim)
print(arrScratch.size)

<class 'numpy.ndarray'> [[0. 0. 0.]
 [0. 0. 0.]]
float64
(2, 3)
2
6


: 

#### zeros_like()
getting the array shape from another array

In [169]:
arrScratch2 = np.zeros_like(arr3d)
print(type(arrScratch), arrScratch)
print(arrScratch.dtype)
print(arrScratch.shape)
print(arrScratch.ndim)
print(arrScratch.size)

<class 'numpy.ndarray'> [[0. 0. 0.]
 [0. 0. 0.]]
float64
(2, 3)
2
6


: 

#### ones()

In [170]:
arrOnes = np.ones((2, 2))
print(arrOnes)

[[1. 1.]
 [1. 1.]]


: 

#### ones_like()

In [171]:
arrOnes2 = np.ones_like(arrOnes)
print(arrOnes2)

[[1. 1.]
 [1. 1.]]


: 

#### empty()
creates array using junk values

In [172]:
arrEmpty = np.empty((2, 2))
print(arrEmpty)

[[1. 1.]
 [1. 1.]]


: 

#### empty_like()

In [173]:
arrEmpty2 = np.empty_like(arrEmpty)
print(arrEmpty2)

[[1. 1.]
 [1. 1.]]


: 

#### full()
creates array using given value

In [174]:
arrFull = np.full((2, 2),"$")
print(arrFull)

[['$' '$']
 ['$' '$']]


: 

In [175]:
arrFull2 = np.full_like(arrFull, np.inf, dtype="float64")
print(arrFull2)

[[inf inf]
 [inf inf]]


: 

## creating ndarray using random values

### random.rand()
generates random values between 0 and 1

In [176]:
arrRand = np.random.rand(2, 2)
print(type(arrRand), arrRand)
print(arrRand.dtype)
print(arrRand.shape)
print(arrRand.ndim)
print(arrRand.size)

<class 'numpy.ndarray'> [[0.81550395 0.10355306]
 [0.01591652 0.43452373]]
float64
(2, 2)
2
4


: 

### random.randint(starting, ending, shape)
creates random values based on the given range

In [177]:
arrRandint = np.random.randint(1, 100, (5, 5))
print(type(arrRandint), arrRandint)
print(arrRandint.dtype)
print(arrRandint.shape)
print(arrRandint.ndim)
print(arrRandint.size)

<class 'numpy.ndarray'> [[ 2 93 53 58 35]
 [ 8 88 73 96 48]
 [13 96 67 68  4]
 [ 2 37 83 27 99]
 [60 40 76 13 24]]
int64
(5, 5)
2
25


: 

### random.uniform(starting, ending, shape)
creates random floating point values based on the given range

In [178]:
arrUniform = np.random.uniform(1, 100, (3, 2))
print(type(arrUniform), arrUniform)
print(arrUniform.dtype)
print(arrUniform.shape)
print(arrUniform.ndim)
print(arrUniform.size)

<class 'numpy.ndarray'> [[44.92284502 31.2185992 ]
 [50.39920972 24.90500458]
 [23.68309585 24.56549638]]
float64
(3, 2)
2
6


: 

### random.arange(first, end, step)


In [179]:
arrArange = np.arange(1, 10, 1).reshape(3,3)
print(type(arrArange))
print(arrArange)
print(arrArange.dtype)
print(arrArange.shape)
print(arrArange.ndim)
print(arrArange.size)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)
2
9


: 

### linspace(start, end(inclusive), number of points to pick)

In [180]:
arrLinspace = np.linspace(1, 10, 5)
print(type(arrLinspace), arrLinspace)
print(arrLinspace.dtype)
print(arrLinspace.shape)
print(arrLinspace.ndim)
print(arrLinspace.size)

<class 'numpy.ndarray'> [ 1.    3.25  5.5   7.75 10.  ]
float64
(5,)
1
5


: 

### logspace(start, end(inclusive), number of points to pick with the given base)

In [181]:
arrLogspace = np.logspace(0, 5, 5)
print(type(arrLogspace))    # outputs values from 10^0 - 10^5 since by default the base is 10
print(arrLogspace)
print(arrLogspace.dtype)
print(arrLogspace.shape)
print(arrLogspace.ndim)
print(arrLogspace.size)

<class 'numpy.ndarray'>
[1.00000000e+00 1.77827941e+01 3.16227766e+02 5.62341325e+03
 1.00000000e+05]
float64
(5,)
1
5


: 

In [182]:
arrLogspace2 = np.logspace(0, 5, 5, base = 2)
print(type(arrLogspace2) )   # outputs values from 2^0 - 2^5
print(arrLogspace2)
print(arrLogspace2.dtype)
print(arrLogspace2.shape)
print(arrLogspace2.ndim)
print(arrLogspace2.size)

<class 'numpy.ndarray'>
[ 1.          2.37841423  5.65685425 13.45434264 32.        ]
float64
(5,)
1
5


: 

## Creating matrix for linear algebra

### diagonal matrix
diag()

In [183]:
arrDiagonal = np.diag([1, 2])
print(arrDiagonal)

[[1 0]
 [0 2]]


: 

### Identity matrix
eye(row, column, k)

In [184]:
arrIdentity = np.eye(3)
print(arrIdentity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


: 

In [185]:
arrIdentity2 = np.eye(4, 4, -1)
print(arrIdentity2)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


: 

## Indexing and slicing
slicing = arr[start : end : step]

In [186]:
slicing = np.array([[1, 2, 3], [4, 5, 6]])
print(slicing)

[[1 2 3]
 [4 5 6]]


: 

first row

In [187]:
print(slicing[0:1,])

[[1 2 3]]


: 

second row

In [188]:
print(slicing[1:2,])

[[4 5 6]]


: 

first column

In [189]:
firstColumn = slicing[::, 0:1]
print(firstColumn)

[[1]
 [4]]


: 

second column

In [190]:
secondColumn = slicing[::, 1:2]
print(secondColumn)

[[2]
 [5]]


: 

first two columns

In [191]:
firstTwoColumns = slicing[::, 1:3]
print(firstTwoColumns)

[[2 3]
 [5 6]]


: 

## copy()

In [192]:
cpy1 = np.array([1, 2, 3, 4, 5])
print(f"cpy1: {cpy1}")

cpy2 = cpy1[1:4].copy()
print(f"cpy2: {cpy2}")

cpy1: [1 2 3 4 5]
cpy2: [2 3 4]


: 

In [193]:
cpy2[1] = 100
print(f"cpy2: {cpy2}")

print(f"cpy1: {cpy1}")

cpy2: [  2 100   4]
cpy1: [1 2 3 4 5]


: 

## Advanced indexing
[[index1, index2, ..., index n]]

In [194]:
advIdx = np.array([1, 2, 3, 4, 5])
val = advIdx[[1, 4]]
print(val)

[2 5]


: 

[[row, row], [col, col]]

In [195]:
advIdx2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
val2 = advIdx2[[0,2], [0, 2]]
print(val2)

[1 9]


: 

In [196]:
print(advIdx2[advIdx2 > 5])

[6 7 8 9]


: 

In [197]:
print(advIdx2[advIdx2 < 5])

[1 2 3 4]


: 

replacing all the values that are greater than 5 with 0

In [198]:
advIdx2[advIdx2 > 5] = 0
print(advIdx2)

[[1 2 3]
 [4 5 0]
 [0 0 0]]


: 

## nditer(array)
iterating every element of a ndarray

In [199]:
iter = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])

for i in np.nditer(iter):
    print(i)

1
2
3
4
5
6
7
8
9


: 

## reshape() and shape

In [200]:
re = np.random.randint(1, 100, size = (10, 5))    # sample - 10, features - 5
print(re)

[[ 3 72 59 95 39]
 [24 25 42  5 86]
 [70 83 97 24 58]
 [63 69 21 70 68]
 [64  7 43 90 66]
 [95 76 89 59 32]
 [61 22 51 72 43]
 [96 80 44 24 11]
 [20 56 45 86 49]
 [88 20 84 76 74]]


: 

In [201]:
re2 = re.reshape(5, 10)
print(re2)

[[ 3 72 59 95 39 24 25 42  5 86]
 [70 83 97 24 58 63 69 21 70 68]
 [64  7 43 90 66 95 76 89 59 32]
 [61 22 51 72 43 96 80 44 24 11]
 [20 56 45 86 49 88 20 84 76 74]]


: 

## flatten
makes the dimension of ndarray to 1 dimension by combining row wise

In [202]:
rowFlatten = re.flatten()
print(rowFlatten)
print(rowFlatten.ndim)

[ 3 72 59 95 39 24 25 42  5 86 70 83 97 24 58 63 69 21 70 68 64  7 43 90
 66 95 76 89 59 32 61 22 51 72 43 96 80 44 24 11 20 56 45 86 49 88 20 84
 76 74]
1


: 

flattening column wise
if "f" is passed as the parameter of order then it would flatten column wise
for row wise the parameter is "c"

In [203]:
columnFlatten = np.ravel(re, order = "f")
print(columnFlatten)

[ 3 24 70 63 64 95 61 96 20 88 72 25 83 69  7 76 22 80 56 20 59 42 97 21
 43 89 51 44 45 84 95  5 24 70 90 59 72 24 86 76 39 86 58 68 66 32 43 11
 49 74]


: 

## array concatenation

In [204]:
con1 = np.random.randint(1, 10, size = (2, 3))
print(con1)

[[7 4 7]
 [5 8 4]]


: 

In [205]:
con2 = np.random.randint(2, 20, size = (2, 3))
print(con2)

[[ 4  7  6]
 [15 12 19]]


: 

### row wise
concatenate((matrix1, matrix2), axis=0)

in order to concatenate, column has to be same for both the arrays

to concatenate row wise, the parameter of axis will be 0

In [206]:
conRow = np.concatenate((con1, con2), axis=0)
print(conRow)

[[ 7  4  7]
 [ 5  8  4]
 [ 4  7  6]
 [15 12 19]]


: 

### column wise
concatenate((matrix1, matrix2), axis=1)

in order to concatenate, row has to be same for both the arrays

In [207]:
conCol = np.concatenate((con1, con2), axis=1)
print(conCol)

[[ 7  4  7  4  7  6]
 [ 5  8  4 15 12 19]]


: 

## transpose matrix

In [208]:
tran = np.array([[1, 2, 3],
                     [4, 5, 6]])
transpose = tran.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


: 

## splitting array

#### np.array_split(arr, no. of split)

In [209]:
array = np.random.randint(1, 10, size = (10,))
print(array)
splittedArray = np.array_split(array, 3)
print(splittedArray)

[4 9 5 8 8 6 2 4 2 1]
[array([4, 9, 5, 8]), array([8, 6, 2]), array([4, 2, 1])]


: 

#### np.split(array, no. of split)
can only be used on arrays where equal divison can take place

In [210]:
arrSplit = np.random.randint(1, 10, size=(10,))
print(arrSplit)
splittedArray2 = np.split(arrSplit, 5)
print(splittedArray2)

[5 7 5 2 5 9 5 1 1 4]
[array([5, 7]), array([5, 2]), array([5, 9]), array([5, 1]), array([1, 4])]


: 

## Arithmetic operator and mathematical functions

In [211]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])
print(f"x: {x}")
print(f"y: {y}")

x: [1 2 3 4 5]
y: [1 2 3 4 5]


: 

### addition, substraction, multiplication, division, mod

In [212]:
print(f"x + y : {x+y}")

print(f"x - y: {x-y}")

print(f"x * y: {x*y}")

print(f"x / y: {x/y}")

print(f"x % y: {x%y}")

x + y : [ 2  4  6  8 10]
x - y: [0 0 0 0 0]
x * y: [ 1  4  9 16 25]
x / y: [1. 1. 1. 1. 1.]
x % y: [0 0 0 0 0]


: 

### trigonometry

In [213]:
sin_x = np.sin(x)
print(f"sin(x): {sin_x}")

cos_x = np.cos(x)
print(f"cos(x): {cos_x}")

tan_x = np.tan(x)
print(f"tan(x): {tan_x}")

sin(x): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos(x): [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
tan(x): [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


: 

### radian to degree conversion

In [214]:
deg_conversion = np.rad2deg(x)
print(f"radian to degree conversion of x: {deg_conversion}")

radian to degree conversion of x: [ 57.29577951 114.59155903 171.88733854 229.18311805 286.47889757]


: 

### degree to radian conversion

In [215]:
rad_conversion = np.deg2rad(deg_conversion)
print(f"degree to radian conversion: {rad_conversion}")

degree to radian conversion: [1. 2. 3. 4. 5.]


: 

### log base 10

In [216]:
log_10 = np.log10(x)
print(f"log base 10 values of x: {log_10}")

log base 10 values of x: [0.         0.30103    0.47712125 0.60205999 0.69897   ]


: 

### log base 2

In [217]:
log_2 = np.log2(x)
print(f"log base 2 values of x: {log_2}")

log base 2 values of x: [0.         1.         1.5849625  2.         2.32192809]


: 

### square root

In [218]:
sqrt = np.sqrt(x)
print(f"square root of x: {sqrt}")

square root of x: [1.         1.41421356 1.73205081 2.         2.23606798]


: 

### sum

In [219]:
sum = np.sum(x)
print(f"sum of x: {sum}")

sum of x: 15


: 

### cumulative sum

In [220]:
cumulative = np.cumulative_sum(x)
print(f"cumulative sum of x: {cumulative}")

cumulative sum of x: [ 1  3  6 10 15]


: 

## Broadcasting

In [221]:
pow2 = x ** 2
print(f"x**2: {pow2}")

sum2 = x + 2
print(f"x+2: {sum2}")

sub2 = x - 2
print(f"x-2: {sub2}")

mul2 = x * 2
print(f"x*2; {mul2}")

div2 = x / 2
print(f"x/2: {div2}")

mod2 = x % 2
print(f"x%2: {mod2}")

x**2: [ 1  4  9 16 25]
x+2: [3 4 5 6 7]
x-2: [-1  0  1  2  3]
x*2; [ 2  4  6  8 10]
x/2: [0.5 1.  1.5 2.  2.5]
x%2: [1 0 1 0 1]


: 

In [222]:
# the row size has to be same for both the arrays in such addition

add1 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

add2 = np.array([1, 2, 3])

add = add1 + add2
print(add)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


: 

## Logical Function

In [223]:
greater = x > y
print(greater)

lower = x < y
print(lower)

greater_equal = x >= y
print(greater_equal)

lower_equal = x <= y
print(lower_equal)

equal = x == y
print(equal)

notEql = x != y
print(notEql)

[False False False False False]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


: 

### all()
finds if all the elements within the array is true

In [224]:
print(np.all(greater_equal))

True


: 

In [225]:
print(np.all(greater))

False


: 

### any()
finds if any of the element within the array is true

In [226]:
print(np.any(greater))

False


: 

In [227]:
print(np.any(greater_equal))

True


: 

## sorting

In [228]:
unsorted = np.array([1, 0, 2, 9, 3, 8, 4, 7, 5, 6])

: 

### inplace sorting

In [229]:
sortedInplace = unsorted.copy()
print(f"before sorting: {sortedInplace}")
sortedInplace.sort()
print(f"after sorting is applied: {sortedInplace}")

before sorting: [1 0 2 9 3 8 4 7 5 6]
after sorting is applied: [0 1 2 3 4 5 6 7 8 9]


: 

### copy sorting

In [230]:
print(f"original array: {unsorted}")
sortedCopy = np.sort(unsorted)
print(f"applying copy sorting: {sortedCopy}")
print(f"original array: {unsorted}")

original array: [1 0 2 9 3 8 4 7 5 6]
applying copy sorting: [0 1 2 3 4 5 6 7 8 9]
original array: [1 0 2 9 3 8 4 7 5 6]


: 

### 2d matrix

In [231]:
twoD = np.array([[8, 2, 4],
                [5, 7, 9], 
                [3, 6, 1]])

: 

#### horizontal sort
axis=1

In [232]:
horizonSort = np.sort(twoD, axis=1)
print(horizonSort)

[[2 4 8]
 [5 7 9]
 [1 3 6]]


: 

#### vertical sort
axis=0

In [233]:
verticalSort = np.sort(twoD, axis=0)
print(verticalSort)

[[3 2 1]
 [5 6 4]
 [8 7 9]]


: 

## np.where(element to be searched)

will return the index val of the searched element

In [234]:
idx1 = np.where(x == 1)
print(idx1)

(array([0]),)


: 

In [235]:
idx2 = np.where(x > 2)
print(idx2)

(array([2, 3, 4]),)


: 

In [236]:
idx4 = np.where(twoD > 5)
print(idx4)

(array([0, 1, 1, 2]), array([0, 1, 2, 1]))


: 

## np.where(condition, x, y)
if condition is true, keep x otherwise replace with y

will return the new array

In [237]:
idx3 = np.where(x > 2, x, 0)
print(idx3)

[0 0 3 4 5]


: 

In [238]:
idx5 = np.where(twoD > 5, twoD, 0)
print(idx5)

[[8 0 0]
 [0 7 9]
 [0 6 0]]


: 

## argmax()
returns the index of the max value in an array

In [239]:
print(x)
maxVal = np.argmax(x)
print(maxVal)

[1 2 3 4 5]
4


: 

## argmin()
returns the index of the min value in an array

In [240]:
print(x)
minVal = np.argmin(x)
print(minVal)

[1 2 3 4 5]
0


: 

## counting in ndarray

In [241]:
count = np.random.randint(1, 100, size=(100,))
print(count)

[15 52 46 33 30 77 13 99 38 47 22 80 41 90 91 55 20 10 57 23 65 57 48 94
 75 93 27 70 61 33 64  9 81 28 96  8 84 70 78 12 82 94 26 68 52 81 97 85
 64 20 62 25 88 35 11 21 87 24 72 86 95 40 25 99 46 10 12 38 21 15 52 21
 26 32 23 45 43 87 45 26 64 95 64 91 97 73 29 56 13 37 55 63 83 24 61 63
 77 14 14 54]


: 

In [242]:
val_greaterThan_5 = np.count_nonzero(count > 50)
print(val_greaterThan_5)

52


: 

In [243]:
val_equal_2 = np.count_nonzero(count == 20)
print(val_equal_2)

2


: 

In [244]:
val_lessThan_50 = np.count_nonzero(count < 50)
print(val_lessThan_50)

48


: 

## np.unique()
provides unique values from the given array

In [245]:
uniqueVal = np.unique(count, return_counts=True)
print(uniqueVal)

(array([ 8,  9, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 32, 33, 35, 37, 38, 40, 41, 43, 45, 46, 47, 48, 52, 54, 55,
       56, 57, 61, 62, 63, 64, 65, 68, 70, 72, 73, 75, 77, 78, 80, 81, 82,
       83, 84, 85, 86, 87, 88, 90, 91, 93, 94, 95, 96, 97, 99]), array([1, 1, 2, 1, 2, 2, 2, 2, 2, 3, 1, 2, 2, 2, 3, 1, 1, 1, 1, 1, 2, 1,
       1, 2, 1, 1, 1, 2, 2, 1, 1, 3, 1, 2, 1, 2, 2, 1, 2, 4, 1, 1, 2, 1,
       1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2]))


: 

In [246]:
# value unpacking since it returns an array
uniqueVal, count = np.unique(count, return_counts=True)
print(uniqueVal)
print(count)

[ 8  9 10 11 12 13 14 15 20 21 22 23 24 25 26 27 28 29 30 32 33 35 37 38
 40 41 43 45 46 47 48 52 54 55 56 57 61 62 63 64 65 68 70 72 73 75 77 78
 80 81 82 83 84 85 86 87 88 90 91 93 94 95 96 97 99]
[1 1 2 1 2 2 2 2 2 3 1 2 2 2 3 1 1 1 1 1 2 1 1 2 1 1 1 2 2 1 1 3 1 2 1 2 2
 1 2 4 1 1 2 1 1 1 2 1 1 2 1 1 1 1 1 2 1 1 2 1 2 2 1 2 2]


: 

## Statistical Analysis

### Data Load

In [247]:
data = np.genfromtxt("marks.csv", delimiter=",", skip_header=1)
print(data)

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]
 [ 13.  14.  15.]
 [ 16.  17.  18.]
 [ 19.  20.  21.]
 [ 22.  23.  24.]
 [ 25.  26.  27.]
 [ 28.  29.  30.]
 [ 31.  32.  34.]
 [ 35.  36.  37.]
 [ 38.  39.  40.]
 [ 41.  42.  43.]
 [ 44.  45.  46.]
 [ 47.  48.  49.]
 [ 50.  51.  52.]
 [ 53.  54.  55.]
 [ 56.  57.  58.]
 [ 59.  60.  61.]
 [ 62.  63.  64.]
 [ 65.  66.  67.]
 [ 68.  69.  70.]
 [ 71.  72.  73.]
 [ 74.  75.  76.]
 [ 77.  78.  79.]
 [ 80.  81.  82.]
 [ 83.  84.  85.]
 [ 86.  87.  88.]
 [ 89.  90.  91.]
 [ 92.  93.  94.]
 [ 95.  96.  97.]
 [ 98.  99. 100.]]


: 

### math marks

In [248]:
mat = data[::, :1]
print(mat)

[[ 1.]
 [ 4.]
 [ 7.]
 [10.]
 [13.]
 [16.]
 [19.]
 [22.]
 [25.]
 [28.]
 [31.]
 [35.]
 [38.]
 [41.]
 [44.]
 [47.]
 [50.]
 [53.]
 [56.]
 [59.]
 [62.]
 [65.]
 [68.]
 [71.]
 [74.]
 [77.]
 [80.]
 [83.]
 [86.]
 [89.]
 [92.]
 [95.]
 [98.]]


: 

In [249]:
print(mat.T)

[[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28. 31. 35. 38. 41. 44. 47. 50. 53.
  56. 59. 62. 65. 68. 71. 74. 77. 80. 83. 86. 89. 92. 95. 98.]]


: 

### finding max math marks

In [250]:
matMax = np.max(mat)
print(matMax)

98.0


: 

### finding min math marks

In [251]:
minMath = np.min(mat)
print(minMath)

1.0


: 

### finding average math marks

In [252]:
avgMath = np.mean(mat)
print(avgMath)

49.666666666666664


: 

### finding median math marks

In [253]:
medianMath = np.median(mat)
print(medianMath)

50.0


: 

### finding standard deviation
the more large standard deviation is, the more scattered the data are

In [254]:
sdMath = np.std(mat)
print(sdMath)

28.95206766747795


: 

## correlation coefficient

In [255]:
studyHours = np.array([1, 2, 3, 4, 5])
examScores = np.array([60, 70, 80, 90, 100])
data = np.array([studyHours, 
                 examScores])
print(data)

[[  1   2   3   4   5]
 [ 60  70  80  90 100]]


: 

In [256]:
correlation = np.corrcoef(data)
print(correlation)

[[1. 1.]
 [1. 1.]]


: 

## Linear Algebra

In [257]:
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

: 

### matrix multiplication

In [258]:
dotProduct = np.dot(matrix1, matrix2)
print(dotProduct)

[[ 58  64]
 [139 154]]


: 

### trace matrix
summation of the diagonal elements

In [259]:
trace = np.trace(matrix1)
print(trace)

6


: 

### determinent of a matrix

In [260]:
matrix3 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

det = np.linalg.det(matrix3)
print(det)

0.0


: 

### rank of a matrix

In [261]:
rank = np.linalg.matrix_rank(matrix3)
print(rank) 

2


: 