# String

In [22]:
str = "hello,hello,"

## type()

In [8]:
print(type(str))

<class 'str'>


## find()

In [4]:
print(str.find("hello"))

0


In [23]:
print(str.rfind("hello"))

6


## capitalize()

In [10]:
print(str.capitalize())

Hello, hello


## upper()

In [8]:
print(str.upper())

HELLO, HELLO


## lower()

In [9]:
print(str.lower())

hello, hello


## count()

In [11]:
print(str.count("hello"))

2


## in

In [12]:
print("hello" in str)

True


## endswith()

In [15]:
print(str.endswith("."))

True


## replace()

In [17]:
print(str.replace("hello", "jello"))

jello, jello.


## len()

In [3]:
print(len(str))

13


## split()

In [7]:
print(str.split(","))

['hello', 'hello', '']


In [10]:
name = ["mashrur", "safir", "shabab"]

## join()

In [12]:
print(" ".join(name))

mashrur safir shabab


## f-string (formatted string literal)

In [16]:
model_accuracy = 0.8357390327854
print(f"{model_accuracy:.2%}")

83.57%


In [20]:
_name = "Mashrur Safir Shabab"
research = "QML"
print(f"This is {_name}. My research intereset or domain lies in {research}")

This is Mashrur Safir Shabab. My research intereset or domain lies in QML


# List

In [75]:
num = [1, 0, 2, 9, 3, 8, 4, 7, 5, 6]

## append()

In [76]:
num.append(10)
print(num)

[1, 0, 2, 9, 3, 8, 4, 7, 5, 6, 10]


## insert()

In [77]:
num.insert(len(num), 11)
print(num)

[1, 0, 2, 9, 3, 8, 4, 7, 5, 6, 10, 11]


## deleting element

### pop()

In [78]:
num.pop()

11

### remove()

In [79]:
num.remove(0)
print(num)

[1, 2, 9, 3, 8, 4, 7, 5, 6, 10]


## sort()

### In ascending order

In [7]:
num.sort()
print(num)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### In descending order

In [8]:
num.sort(reverse=True)
print(num)

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


## reverse()

In [9]:
num.reverse()
print(num)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## List as stack

In [18]:
stack = []

### stack push

In [54]:
stack.append(1)
print(stack)

stack.append(2)
print(stack)

stack.append(3)
print(stack)

[1]
[1, 2]
[1, 2, 3]


### stack pop

In [55]:
print(f"popped - {stack.pop()}")
print(f"top - {stack[-1]}\n")

print(f"popped - {stack.pop()}")
print(f"top - {stack[-1]}\n")

print(f"popped - {stack.pop()}")
# print(f"top - {stack[-1]}\n")

popped - 3
top - 2

popped - 2
top - 1

popped - 1


## List as Queue

### Queue push

In [42]:
queue = []

In [49]:
queue.append(1)
print(queue)

queue.append(2)
print(queue)

queue.append(3)
print(queue)

[1]
[1, 2]
[1, 2, 3]


### Queue pop

In [50]:
print(f"popped - {queue.pop(0)}")
print(f"top - {queue[0]} \n")

print(f"popped - {queue.pop(0)}")
print(f"top - {queue[0]} \n")

print(f"popped - {queue.pop(0)}")
# print(f"top element - {queue[0]} \n")

popped - 1
top - 2 

popped - 2
top - 3 

popped - 3


## List Comprehension

list = [expression loop condition]

In [57]:
even = [i for i in range(101) if i % 2 == 0]
print(even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [58]:
fruits = ["apple", "orange", "watermellon"]
upperFruits = [fruit.upper() for fruit in fruits]
print(upperFruits)

['APPLE', 'ORANGE', 'WATERMELLON']


# Tuple

ordered, immutable

In [81]:
a = (10,)
print(type(a), a, "\n")

b = tuple([1, 2, 3, 4, 5])
print(type(b), b, "\n")

<class 'tuple'> (10,) 

<class 'tuple'> (1, 2, 3, 4, 5) 



In [85]:
tup = (1, 2, 3, 3.5, True, "tuple")
print(type(tup), tup)

<class 'tuple'> (1, 2, 3, 3.5, True, 'tuple')


## count()

In [89]:
tup.count(True)

2

## index()

In [91]:
tup.index(1)

0

# Set

stores unique elements, unordered, mutable

In [93]:
Set = set()
print(type(Set), set)

<class 'set'> <class 'set'>


In [105]:
_set = {1, 2.5, "set", True}
print(type(_set), _set)

<class 'set'> {'set', 2.5, 1}


## add()

In [106]:
_set.add(False)
print(_set)

{False, 'set', 2.5, 1}


## pop()

In [107]:
_set.pop()

False

## remove()

In [108]:
_set.remove(1)
print(_set)

{'set', 2.5}


In [109]:
aSet = {1, 2, 3}
bSet = {2, 3, 4}

## union()

In [110]:
aSet.union(bSet)

{1, 2, 3, 4}

## intersection

In [111]:
aSet.intersection(bSet)

{2, 3}

## isdisjoint()

In [112]:
aSet.isdisjoint(b)

False

## issubset()

In [113]:
cSet = {1, 2}
dSet = {1, 2, 3, 4}

cSet.issubset(dSet)

True

# Dictionary


mutable, unordered

In [114]:
dictionary = {}
print(type(dictionary), dictionary)

<class 'dict'> {}


In [139]:
dic = {"name" : "Safir",
    0 : "salary",
    1.0: "season",
    "Research Domains" : ["AI/ML", "QC", True, False, 0, 1.5],
    "isEmployed" : False,
    "edu" : "BracU",
    "edu" : {
        "uni" : "BracU",
        "school" : "SHES"
    },
    True : (1, 2, 3, 3.5, True, "tuple"),
    "set" : {1, 2.5, "set", True}}

print(type(dic), dic)

<class 'dict'> {'name': 'Safir', 0: 'salary', 1.0: (1, 2, 3, 3.5, True, 'tuple'), 'Research Domains': ['AI/ML', 'QC', True, False, 0, 1.5], 'isEmployed': False, 'edu': {'uni': 'BracU', 'school': 'SHES'}, 'set': {'set', 2.5, 1}}


## get()

In [140]:
dic.get("edu", 0)

{'uni': 'BracU', 'school': 'SHES'}

## update()

In [141]:
dic.update({"ai/ml" : ["NLP", "CV"]})
dic

{'name': 'Safir',
 0: 'salary',
 1.0: (1, 2, 3, 3.5, True, 'tuple'),
 'Research Domains': ['AI/ML', 'QC', True, False, 0, 1.5],
 'isEmployed': False,
 'edu': {'uni': 'BracU', 'school': 'SHES'},
 'set': {1, 2.5, 'set'},
 'ai/ml': ['NLP', 'CV']}

## del

In [142]:
del dic["ai/ml"]
dic

{'name': 'Safir',
 0: 'salary',
 1.0: (1, 2, 3, 3.5, True, 'tuple'),
 'Research Domains': ['AI/ML', 'QC', True, False, 0, 1.5],
 'isEmployed': False,
 'edu': {'uni': 'BracU', 'school': 'SHES'},
 'set': {1, 2.5, 'set'}}

## copy()

In [143]:
dic2 = dic.copy()
dic2

{'name': 'Safir',
 0: 'salary',
 1.0: (1, 2, 3, 3.5, True, 'tuple'),
 'Research Domains': ['AI/ML', 'QC', True, False, 0, 1.5],
 'isEmployed': False,
 'edu': {'uni': 'BracU', 'school': 'SHES'},
 'set': {1, 2.5, 'set'}}

Key has to be immutable <br>
value can be anything

In [144]:
dic3 = {[1, 2, 3] : "a"}

TypeError: unhashable type: 'list'

In [145]:
dic3 = {(1, 2, 3) : "a"}
dic3

{(1, 2, 3): 'a'}

## keys()
## values()

In [151]:
dic.keys()

dict_keys(['name', 0, 1.0, 'Research Domains', 'isEmployed', 'edu', 'set'])

In [152]:
dic.values()

dict_values(['Safir', 'salary', (1, 2, 3, 3.5, True, 'tuple'), ['AI/ML', 'QC', True, False, 0, 1.5], False, {'uni': 'BracU', 'school': 'SHES'}, {'set', 2.5, 1}])

## items()

In [156]:
for key, value in dic.items():
    print(f"{key} - {value}")

name - Safir
0 - salary
1.0 - (1, 2, 3, 3.5, True, 'tuple')
Research Domains - ['AI/ML', 'QC', True, False, 0, 1.5]
isEmployed - False
edu - {'uni': 'BracU', 'school': 'SHES'}
set - {'set', 2.5, 1}


## Dictionary comprihension

In [157]:
coordinates = [(10.5, 1), (2.5, 8), (77, 45)]
locations = ["Khulna", "Dhaka", "Chittagong"]

exactLocation = {coor : loc for coor, loc in zip(coordinates, locations)}
print(exactLocation)

{(10.5, 1): 'Khulna', (2.5, 8): 'Dhaka', (77, 45): 'Chittagong'}


# Functions

## Keyword argument

In [4]:
def sum (a, b, c = 30):
    print(a, b, c)
    return a + b + c

output = sum(b = 10, a = 20) + 10
print(output)

20 10 30
70


## Variable Length Argument

In [13]:
def sum (*args):
    print(args)
    for i in args:
        print(i)

sum(1, 2, 3)

(1, 2, 3)
1
2
3


## Keyword Arguments

In [23]:
def info (**kwargs):
    print(kwargs)
    for key, value in kwargs.items():
        print(f"{key} : {value}")

info(a = 10, b = 20)

{'a': 10, 'b': 20}
a : 10
b : 20


## Value unpacking

In [30]:
def a():
    return 1, 2

print(type(a()), a())

x, y = a()
print(x, y)

<class 'tuple'> (1, 2)
1 2


In [33]:
def b():
    a = [1, 2, 3]
    b = [1, 2, 3]
    return a, b

print(type(b()), b())

<class 'tuple'> ([1, 2, 3], [1, 2, 3])


In [35]:
def c():
    return {1, 2, 3}

print(type(c()), c())

<class 'set'> {1, 2, 3}


## Iterator

In [38]:
sIterator = {1, 2, 3}
s_iterator = iter(sIterator)
print(type(s_iterator))
print(next(s_iterator))
print(next(s_iterator))
print(next(s_iterator))
print(next(s_iterator))

<class 'set_iterator'>
1
2
3


StopIteration: 

## Generator

In [45]:
listGen = [i for i in range(100)]

def data_loader(chunk_size, lst):
    for i in range(0, len(lst), chunk_size):
        yield lst[i:i+chunk_size]

data = data_loader(5, listGen) 
print(type(data))
print(next(data))
print(next(data))
print(next(data))
print(next(data))

<class 'generator'>
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]
[15, 16, 17, 18, 19]


## Lambda Function

In [47]:
isEven = lambda x : x % 2 == 0
print(isEven(2))

True


## map()

In [60]:
name = "mashrur safir shabab"
strMap = list(map(str.upper, name))
print(strMap)

name2 = " ".join(strMap)
print(name2)

['M', 'A', 'S', 'H', 'R', 'U', 'R', ' ', 'S', 'A', 'F', 'I', 'R', ' ', 'S', 'H', 'A', 'B', 'A', 'B']
M A S H R U R   S A F I R   S H A B A B


In [63]:
lstMap = [1, 2, 3]

lstMap2 = list(map(lambda i : i**2 if i % 2 == 0 else i/2, lstMap))
print(lstMap2)

[0.5, 4, 1.5]


## filter()

In [64]:
dataFilter = [0, None, 1, None, " ", None, [], None, {}, None, (), None, True, None, False]
cleaned_data = list(filter(None, dataFilter))
print(cleaned_data)

[1, ' ', True]


In [71]:
numFilter = [i for i in range(100)]
above50 = list(filter(lambda x : x > 50, numFilter))
print(above50)

[51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [73]:
even = list(filter(lambda x : x % 2 == 0, numFilter))
print(even)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [74]:
name = "mashrur safir shabab"
vowel = list(filter(lambda x : x in "aeiou", name))
print(vowel)

['a', 'u', 'a', 'i', 'a', 'a']


In [77]:
fruits = ["apple", "orange", "pineapple"]
filtering = list(filter(lambda x : len(x) > 6, fruits))
print(filtering)

['pineapple']


## reduce()

In [67]:
from functools import reduce
listReduce = [1, 2, 3, 4, 5]
sum = reduce(lambda x, y : x + y, listReduce)
print(sum)

15


In [69]:
maxVal = reduce(lambda x, y : x if x > y else y, listReduce)
print(maxVal)

5


# File I/O

In [42]:
file = open("file.txt", "r")

## read()

In [8]:
content1 = file.read()
print(content1)

Hello, 
this is Mashrur Safir Shabab.


## readlines()

In [11]:
content2 = file.readlines()
print(content2)

['Hello, \n', 'this is Mashrur Safir Shabab.']


### using map()

In [37]:
content3 = list(map(str.strip, file))
print(content3)

['Hello,', 'this is Mashrur Safir Shabab.', 'What we know is a drop in the ocean', '']


### using filter()

In [43]:
content4 = list(filter(lambda x : len(x) > 1, file))
print(content4)

['Hello, \n', 'this is Mashrur Safir Shabab.\n', 'What we know is a drop in the ocean\n']


In [14]:
print(file.closed)

file.close()

print(file.closed)

False
True


## with (best practice)

In [16]:
with open("file.txt", "r") as file:
    content = file.readlines()
    print(content)

print(file.closed)

['Hello, \n', 'this is Mashrur Safir Shabab.']
True


In [17]:
with open("file.txt", "r") as file:
    for line in file:
        print(line)

Hello, 

this is Mashrur Safir Shabab.


In [19]:
with open("file.txt", "r") as file:
    for line in file:
        print(line, end = "")

Hello, 
this is Mashrur Safir Shabab.

In [24]:
with open("file.txt", "r") as file:
    for line in file:
        l = line.strip()
        print(l)

Hello,
this is Mashrur Safir Shabab.


## write()

overwrite

In [26]:
with open("test.txt", "w") as file:
    file.write("hey!\n")
    file.write("I am shabab")

append

In [29]:
with open("file.txt", "a") as file:
    file.write("What we know is a drop in the ocean\n")

## writelines()

In [44]:
txt = ["hello\n", "hi\n", "bye\n"]
with open("file.txt", "a") as file:
    file.writelines(txt)


## File Pointer

### tell()
### seek()

In [54]:
with open("helloWorld.txt", "r") as file:
    print(file.tell())
    print(file.seek(6))
    print(file.tell())
    print(file.read())
    print(file.tell())
    print(file.seek(0))
    print(file.read())

0
6
6
World !
13
0
Hello World !


exercise

In [85]:
from functools import reduce

with open("file.txt", "r") as file:
    
    # Counting number of lines
    countLines = file.readlines()
    print(countLines)
    l = len(countLines)
    print(f"Total number of lines: {l}\n")

    # Counting number of words
    countWords = list(map(lambda x : len(x.split()), countLines))
    print(countWords)
    countWords = reduce(lambda x, y : x + y, countWords)
    print(f"Total number of words: {countWords}\n")

    # Counting number of characters
    countChars = list(map(str.strip, countLines))
    print(countChars)
    countChars = list(map(lambda x : x.replace(" ", ""), countChars))
    print(countChars)
    countChars = list(map(lambda x : len(x), countChars))
    print(countChars)
    countChars = reduce(lambda x, y : x + y, countChars)
    print(f"Total number of characters {countChars}")

    # saving all the counts in file.txt
    with open("file.txt", "a") as file:
        file.write(f"Total Number of lines: {l}\n")
        file.write(f"Total number of words: {countWords}\n")
        file.write(f"Total number of characters: {countChars}\n")


['what we know is a drop in the ocean\n', '\n', 'hey, \n', 'this is shabab!\n']
Total number of lines: 4

[9, 0, 1, 3]
Total number of words: 13

['what we know is a drop in the ocean', '', 'hey,', 'this is shabab!']
['whatweknowisadropintheocean', '', 'hey,', 'thisisshabab!']
[27, 0, 4, 13]
Total number of characters 44


## w+ a+ r+

In [86]:
with open("file.txt", "a+") as file:
    file.write("Hello World!")
    print(file.tell())
    print(file.read())
    print(file.seek(0))
    print(file.tell())
    print(file.read())

153

0
0
what we know is a drop in the ocean

hey, 
this is shabab!
Total Number of lines: 4
Total number of words: 13
Total number of characters: 44
Hello World!


# Exception Handling

In [107]:
n = int(input())

try:
    a = 10/n
    # a = x
except ZeroDivisionError as divErr:
    print(divErr)
except Exception as e:
    print(e)
else:
    print("No exception raised")
finally:
    print("User input taken")


print("Hello there!")

No exception raised
User input taken
Hello there!


# OOP

## Classes and Objects

In [25]:
class Phone:
    # default attribute
    category = "electronics"

apple = Phone()
mtotorolla = Phone()
blueberry = Phone()

print(f"apple - {apple.category}")
print(f"mtotorolla - {mtotorolla.category}")
print(f"blueberry - {blueberry.category}")
print()
# changing the default category of apple
apple.category = "ultra electronics"
print(f"apple - {apple.category}")

apple - electronics
mtotorolla - electronics
blueberry - electronics

apple - ultra electronics


## Constructor

In [30]:
class Dog:
    # constructor
    def __init__(self):
        print("function got called")

dog1 = Dog()    # constructor gets called after an object is created
dog1.name = "tom"
print(dog1.name)

function got called
tom


In [31]:
class Phone:
    # default class attribute
    category = "electronics"

    # constructor
    def __init__(self, model, battery, camera, battery_percentage = 100):
        #assigning instance attribue
        self.model = model
        self.battery = battery
        self.camera = camera
        self.battery_percentage = battery_percentage

apple = Phone("I17", 3000, 30)

print(f"default category - {apple.category}")
print(f"model - {apple.model}")
print(f"battery - {apple.battery}")
print(f"camera - {apple.camera}")
print(f"battery percentage - {apple.battery_percentage}")

default category - electronics
model - I17
battery - 3000
camera - 30
battery percentage - 100


### dir()
lists all methods and attributes of the class object

In [32]:
dir(apple)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'battery',
 'battery_percentage',
 'camera',
 'category',
 'model']

## Methods

In [37]:
# base / parent class
class Phone:
    # class attribute
    category = "electronics"

    # constructor
    def __init__(self, model, battery, camera, battery_percentage = 100):
        # instance attribues
        self.model = model
        self.battery = battery
        self.camera = camera
        self.battery_percentage = battery_percentage

    # instance methods can access both class and instance attribute
    # instance method
    def photoCapture(self, capture):
        if self.battery_percentage < 0:
            print("No charge")
        self.battery_percentage -= capture
        print(f"Phote captured in {self.model}")

    # instance method
    def charge(self, hour):
        print(f"charge duration {hour} hour(s)")

    @classmethod
    def info(self):
        # class methods can only access class attribues
        print(self.category)

apple = Phone("apple", 3000, 30)
samsung = Phone("S7", 40000, 40)
apple.charge(2)
apple.photoCapture(10)
print(f"apple battery percentage - {apple.battery_percentage}")
print(f"samsung battery percentage - {samsung.battery_percentage}")
apple.info()

charge duration 2 hour(s)
Phote captured in apple
apple battery percentage - 90
samsung battery percentage - 100
electronics


## Inheritence

In [45]:
# derived / child class
class SmartPhone(Phone):
    def __init__(self, model, battery, camera, processor):
        super().__init__(model, battery, camera)
        self.processor = processor

    def charge(self, hours):
        print("fast charging in progress")
        super().charge(hours)

nothing = SmartPhone("nothing", 1000, 10, "SnapDragon")
print(f"model - {nothing.model}")
print(f"battery - {nothing.battery}")
print(f"battery - {nothing.battery}")
print(f"camera - {nothing.camera}")
print(f"processor - {nothing.processor}")
print(f"battery percentage - {nothing.battery_percentage}")

nothing.photoCapture(30)
print(f"battery percentage after photo capture - {nothing.battery_percentage}")

nothing.charge(10)

model - nothing
battery - 1000
battery - 1000
camera - 10
processor - SnapDragon
battery percentage - 100
Phote captured in nothing
battery percentage after photo capture - 70
fast charging in progress
charge duration 10 hour(s)


### Multiple Inheritence

In [68]:
class CoolingMechanism:
    def __init__(self, method):
        self.method = method

    def coolingOn(self):
        print(f"The system is being cooled by {self.method}")

In [75]:
class SmartPhone_CoolingMechanism(SmartPhone, CoolingMechanism):
    def __init__(self, model, battery, camera, processor, method):
        SmartPhone.__init__(self, model, battery, camera, processor)
        CoolingMechanism.__init__(self, method)

xiaomi = SmartPhone_CoolingMechanism("xiaomi", 1000, 10, "SnapDragon", "Nitro")
print(f"model - {xiaomi.model}")
print(f"battery - {xiaomi.model}")
print(f"camera - {xiaomi.camera}")
print(f"processor - {xiaomi.processor}")
print(f"battery - {xiaomi.battery_percentage}")
xiaomi.photoCapture(10)
print(f"battery after photo capture - {xiaomi.battery_percentage}")
xiaomi.charge(10)
xiaomi.coolingOn()


model - xiaomi
battery - xiaomi
camera - 10
processor - SnapDragon
battery - 100
Phote captured in xiaomi
battery after photo capture - 90
fast charging in progress
charge duration 10 hour(s)
The system is being cooled by Nitro


## Polymorphism

In [80]:
class Camera:
    def __init__(self, name):
        self.name = name

    def capture(self):
        print("a photo is captured")

class Smart(Camera):
    def __init__(self, name, resolution):
        super().__init__(name)
        self.resolution = resolution

    # method overriding
    def capture(self):
        print(f"A photo is being captured by a {self.name}")

class DSLR(Camera):
    def __init__(self, name, resolution):
        super().__init__(name)
        self.resolution = resolution

    # method overriding
    def capture(self):
        print(f"A photo is being captured by a {self.name}")

class Drone(Camera):
    def __init__(self, name, resolution):
        super().__init__(name)
        self.resolution = resolution

    # method overriding
    def capture(self):
        print(f"A photo is being captured by a {self.name}")


smart = Smart("smart_phone", 10)
dslr = DSLR("DSLR", 10)
drone = Drone("Drone", 10)

smart.capture()
dslr.capture()
drone.capture()


A photo is being captured by a smart_phone
A photo is being captured by a DSLR
A photo is being captured by a Drone


## Encapsulation

In [11]:
class Mobile:
    def __init__(self, name, model, imei):
        self.name = name
        self.model = model
        self.__imei = imei    # private

    def charge(self):
        print("Phone is charging")

iphone = Mobile("iphone", 17, 102030)

print(f"Default IMEI: {iphone.__imei}")
iphone.imei = "1x1x1x"
print(f"Updated IMEI: {iphone.__imei}")

AttributeError: 'Mobile' object has no attribute '__imei'

In [17]:
class Mobile:
    def __init__(self, name, model, imei):
        self.name = name
        self.model = model
        self.__imei = imei    # private

    def getter(self):
        return self.__imei

iphone = Mobile("iphone", 17, 102030)
print(f"Default IMEI: {iphone.getter()}")
iphone.__imei = "1x2x3x"
print(f"Changed IMEI: {iphone.getter()}")
# imei didn't change and now can only be accessed by getter method

Default IMEI: 102030
Changed IMEI: 102030


In [18]:
class Mobile:
    def __init__(self, name, model, imei):
        self.__imei = imei    # private

    def getter(self):
        return self.__imei
    
    def setter(self, imei):
        self.__imei = imei

iphone = Mobile("iphone", 17, 102030)
print(f"Default IMEI: {iphone.getter()}")
iphone.setter("1x2x3x")
print(f"Changed IMEI: {iphone.getter()}")

Default IMEI: 102030
Changed IMEI: 1x2x3x


## Abstraction

In [20]:
from ABC import abc, abstractmethod

class Telephone(ABC):

    @abstractmethod
    def makeCalls(self):
        pass

    @abstractmethod
    def capturePhoto(self):
        pass


class iphone(Telephone):

    def makeCalls(self):
        print("Make call")

phone = iphone()
phone.makeCalls()

ModuleNotFoundError: No module named 'ABC'

# ndarray

In [32]:
import numpy as np

## ndarray declaration 

### 1d array

In [55]:
arr1d = np.array([1, 2, 3, 4, 5])
print(type(arr1d), arr1d)
print(arr1d.ndim)
print(arr1d.shape)
print(arr1d.dtype)
print(arr1d.size)

<class 'numpy.ndarray'> [1 2 3 4 5]
1
(5,)
int64
5


### 2d array

In [57]:
arr2d = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.dtype)
print(arr2d.size)

2
(2, 3)
int64
6


### 3d array

In [58]:
arr3d = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11, 12]]])
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.dtype)
print(arr3d.size)

3
(2, 2, 3)
int64
12


## data type

### upcasting to float

In [59]:
floatArr = np.array([1, 2, 3.5])
print(floatArr.dtype)

float64


### upcasting to string

In [60]:
stringArr = np.array([1, 2, "3"])
print(stringArr.dtype)

<U21


### selecting a data type for an array

In [65]:
arrInt8 = np.array([1, 2, 3], dtype=np.int8)
print(arrInt8.dtype)

int8


### changing data type of an exisitng arr

In [70]:
arrFloat16 = arrFloat16.astype(np.float16)
print(arrFloat16.dtype, arrFloat16)

float16 [1. 2. 3.]


## nd array creation from existing data

### list

In [72]:
lst = [1, 2, 3.5]
arrLst = np.array(lst)
print(type(arrLst))
print(arrLst.dtype)


<class 'numpy.ndarray'>
float64


### tuple

In [77]:
tup = (1, 2, 3)
arrTup = np.array(tup)
print(type(arrTup), arrTup)
print(arrTup.dtype)
print(arrTup.shape)
print(arrTup.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1


### set

In [78]:
_set = {1, 2, 3}    
arrSet = np.array(_set)    # treats the whole set as one single element
print(type(arrSet), arrSet)
print(arrSet.dtype)
print(arrSet.shape)
print(arrSet.ndim)

<class 'numpy.ndarray'> {1, 2, 3}
object
()
0


In [79]:
arrSet = np.array(list(_set))    # thus, the set has to be typecasted to a list first
print(type(arrSet), arrSet)
print(arrSet.dtype)
print(arrSet.shape)
print(arrSet.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1


### dictionary

In [3]:
dic = {"a" : 1, "b" : 2, "c" : 3}
items = dic.items()
print(f"items: {items}")

keys = dic.keys()
print(f"keys: {keys}")

values = dic.values()
print(f"values: {values}")

items: dict_items([('a', 1), ('b', 2), ('c', 3)])
keys: dict_keys(['a', 'b', 'c'])
values: dict_values([1, 2, 3])


In [89]:
arrKeys = np.array(list(keys))    # treats the list within the tuple as one single element. thus, the tuple has to be typecasted to a list first
print(type(arrKeys), arrKeys)
print(arrKeys.dtype)
print(arrKeys.shape)
print(arrKeys.ndim)

<class 'numpy.ndarray'> ['a' 'b' 'c']
<U1
(3,)
1


In [90]:
arrValues = np.array(list(values))    # treats the list within the tuple as one single element. thus, the tuple has to be typecasted to a list first
print(type(arrValues), arrValues)
print(arrValues.dtype)
print(arrValues.shape)
print(arrValues.ndim)

<class 'numpy.ndarray'> [1 2 3]
int64
(3,)
1


In [93]:
arrItems = np.array(items)
print(type(arrItems), arrItems)
print(arrItems.dtype)
print(arrItems.shape)
print(arrItems.ndim)

<class 'numpy.ndarray'> dict_items([('a', 1), ('b', 2), ('c', 3)])
object
()
0


### creating ndarray from scratch

#### zeros()

In [96]:
arrScratch = np.zeros((2, 3))
print(type(arrScratch), arrScratch)
print(arrScratch.dtype)
print(arrScratch.shape)
print(arrScratch.ndim)
print(arrScratch.size)

<class 'numpy.ndarray'> [[0. 0. 0.]
 [0. 0. 0.]]
float64
(2, 3)
2
6


#### zeros_like()
getting the array shape from another array

In [97]:
arrScratch2 = np.zeros_like(arr3d)
print(type(arrScratch), arrScratch)
print(arrScratch.dtype)
print(arrScratch.shape)
print(arrScratch.ndim)
print(arrScratch.size)

<class 'numpy.ndarray'> [[0. 0. 0.]
 [0. 0. 0.]]
float64
(2, 3)
2
6


#### ones()

In [99]:
arrOnes = np.ones((2, 2))
print(arrOnes)

[[1. 1.]
 [1. 1.]]


#### ones_like()

In [100]:
arrOnes2 = np.ones_like(arrOnes)
print(arrOnes2)

[[1. 1.]
 [1. 1.]]


#### empty()
creates array using junk values

In [115]:
arrEmpty = np.empty((2, 2))
print(arrEmpty)

[[1. 1.]
 [1. 1.]]


#### empty_like()

In [116]:
arrEmpty2 = np.empty_like(arrEmpty)
print(arrEmpty2)

[[1. 1.]
 [1. 1.]]


#### full()
creates array using given value

In [133]:
arrFull = np.full((2, 2),"$")
print(arrFull)

[['$' '$']
 ['$' '$']]


In [134]:
arrFull2 = np.full_like(arrFull, np.inf, dtype="float64")
print(arrFull2)

[[inf inf]
 [inf inf]]


## creating ndarray using random values

### random.rand()
generates random values between 0 and 1

In [145]:
arrRand = np.random.rand(2, 2)
print(type(arrRand), arrRand)
print(arrRand.dtype)
print(arrRand.shape)
print(arrRand.ndim)
print(arrRand.size)

<class 'numpy.ndarray'> [[0.10349932 0.08420218]
 [0.21101462 0.29465927]]
float64
(2, 2)
2
4


### random.randint(starting, ending, shape)
creates random values based on the given range

In [157]:
arrRandint = np.random.randint(1, 100, (5, 5))
print(type(arrRandint), arrRandint)
print(arrRandint.dtype)
print(arrRandint.shape)
print(arrRandint.ndim)
print(arrRandint.size)

<class 'numpy.ndarray'> [[86 61 79  4 56]
 [45 54 97 71 41]
 [45 91 14 19 38]
 [82 26 31 16 89]
 [14 96 34 49 81]]
int64
(5, 5)
2
25


### random.uniform(starting, ending, shape)
creates random floating point values based on the given range

In [158]:
arrUniform = np.random.uniform(1, 100, (3, 2))
print(type(arrUniform), arrUniform)
print(arrUniform.dtype)
print(arrUniform.shape)
print(arrUniform.ndim)
print(arrUniform.size)

<class 'numpy.ndarray'> [[89.31783964 78.22478313]
 [ 5.65688642 29.58448072]
 [68.17790865 97.24434284]]
float64
(3, 2)
2
6


### random.arange(first, end, step)


In [189]:
arrArange = np.arange(1, 10, 1).reshape(3,3)
print(type(arrArange))
print(arrArange)
print(arrArange.dtype)
print(arrArange.shape)
print(arrArange.ndim)
print(arrArange.size)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)
2
9


### linspace(start, end(inclusive), number of points to pick)

In [180]:
arrLinspace = np.linspace(1, 10, 5)
print(type(arrLinspace), arrLinspace)
print(arrLinspace.dtype)
print(arrLinspace.shape)
print(arrLinspace.ndim)
print(arrLinspace.size)

<class 'numpy.ndarray'> [ 1.    3.25  5.5   7.75 10.  ]
float64
(5,)
1
5


### logspace(start, end(inclusive), number of points to pick with the given base)

In [188]:
arrLogspace = np.logspace(0, 5, 5)
print(type(arrLogspace))    # outputs values from 10^0 - 10^5 since by default the base is 10
print(arrLogspace)
print(arrLogspace.dtype)
print(arrLogspace.shape)
print(arrLogspace.ndim)
print(arrLogspace.size)

<class 'numpy.ndarray'>
[1.00000000e+00 1.77827941e+01 3.16227766e+02 5.62341325e+03
 1.00000000e+05]
float64
(5,)
1
5


In [187]:
arrLogspace2 = np.logspace(0, 5, 5, base = 2)
print(type(arrLogspace2) )   # outputs values from 2^0 - 2^5
print(arrLogspace2)
print(arrLogspace2.dtype)
print(arrLogspace2.shape)
print(arrLogspace2.ndim)
print(arrLogspace2.size)

<class 'numpy.ndarray'>
[ 1.          2.37841423  5.65685425 13.45434264 32.        ]
float64
(5,)
1
5


## Creating matrix for linear algebra

### diagonal matrix
diag()

In [184]:
arrDiagonal = np.diag([1, 2])
print(arrDiagonal)

[[1 0]
 [0 2]]


### Identity matrix
eye(row, column, k)

In [186]:
arrIdentity = np.eye(3)
print(arrIdentity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [196]:
arrIdentity2 = np.eye(4, 4, -1)
print(arrIdentity2)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## Indexing and slicing
slicing = arr[start : end : step]

In [35]:
slicing = np.array([[1, 2, 3], [4, 5, 6]])
print(slicing)

[[1 2 3]
 [4 5 6]]


first row

In [23]:
print(slicing[0:1,])

[[1 2 3]]


second row

In [24]:
print(slicing[1:2,])

[[4 5 6]]


first column

In [30]:
firstColumn = slicing[::, 0:1]
print(firstColumn)

[[1]
 [4]]


second column

In [31]:
secondColumn = slicing[::, 1:2]
print(secondColumn)

[[2]
 [5]]


first two columns

In [37]:
firstTwoColumns = slicing[::, 1:3]
print(firstTwoColumns)

[[2 3]
 [5 6]]


## copy()

In [40]:
cpy1 = np.array([1, 2, 3, 4, 5])
print(f"cpy1: {cpy1}")

cpy2 = cpy1[1:4].copy()
print(f"cpy2: {cpy2}")

cpy1: [1 2 3 4 5]
cpy2: [2 3 4]


In [41]:
cpy2[1] = 100
print(f"cpy2: {cpy2}")

print(f"cpy1: {cpy1}")

cpy2: [  2 100   4]
cpy1: [1 2 3 4 5]


## Advanced indexing
[[index1, index2, ..., index n]]

In [42]:
advIdx = np.array([1, 2, 3, 4, 5])
val = advIdx[[1, 4]]
print(val)

[2 5]


[[row, row], [row, col]]

In [49]:
advIdx2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
val2 = advIdx2[[0,2], [0, 2]]
print(val2)

[1 9]


In [52]:
print(advIdx2[advIdx2 > 5])

[6 7 8 9]


In [53]:
print(advIdx2[advIdx2 < 5])

[1 2 3 4]


replacing all the values that are greater than 5 with 0

In [54]:
advIdx2[advIdx2 > 5] = 0
print(advIdx2)

[[1 2 3]
 [4 5 0]
 [0 0 0]]


## nditer(array)
iterating every element of a ndarray

In [58]:
iter = np.array([[1, 2, 3], 
                [4, 5, 6],
                [7, 8, 9]])

for i in np.nditer(iter):
    print(i)

1
2
3
4
5
6
7
8
9


## reshape() and shape

In [72]:
re = np.random.randint(1, 100, size = (10, 5))    # sample - 10, features - 5
print(re)

[[ 3 64 60 32  5]
 [26 35 63 71  4]
 [94 74 76 83 63]
 [76  6 24 47 23]
 [48 12 54 91 75]
 [76 23 68 87 75]
 [11 54 93  7 75]
 [55 11 35 65 13]
 [99 29 53  9 52]
 [89 64 44 53 25]]


In [73]:
re2 = re.reshape(5, 10)
print(re2)

[[ 3 64 60 32  5 26 35 63 71  4]
 [94 74 76 83 63 76  6 24 47 23]
 [48 12 54 91 75 76 23 68 87 75]
 [11 54 93  7 75 55 11 35 65 13]
 [99 29 53  9 52 89 64 44 53 25]]


## flatten
makes the dimension of ndarray to 1 dimension by combining row wise

In [74]:
rowFlatten = re.flatten()
print(rowFlatten)
print(rowFlatten.ndim)

[ 3 64 60 32  5 26 35 63 71  4 94 74 76 83 63 76  6 24 47 23 48 12 54 91
 75 76 23 68 87 75 11 54 93  7 75 55 11 35 65 13 99 29 53  9 52 89 64 44
 53 25]
1


flattening column wise
if "f" is passed as the parameter of order then it would flatten column wise
for row wise the parameter is "c"

In [75]:
columnFlatten = np.ravel(re, order = "f")
print(columnFlatten)

[ 3 26 94 76 48 76 11 55 99 89 64 35 74  6 12 23 54 11 29 64 60 63 76 24
 54 68 93 35 53 44 32 71 83 47 91 87  7 65  9 53  5  4 63 23 75 75 75 13
 52 25]


## array concatenation

In [76]:
con1 = np.random.randint(1, 10, size = (2, 3))
print(con1)

[[7 2 9]
 [6 3 6]]


In [77]:
con2 = np.random.randint(2, 20, size = (2, 3))
print(con2)

[[15  2  3]
 [ 9 18 11]]


### row wise
concatenate((matrix1, matrix2), axis=0)

in order to concatenate, column has to be same for both the arrays

to concatenate row wise, the parameter of axis will be 0

In [79]:
conRow = np.concatenate((con1, con2), axis=0)
print(conRow)

[[ 7  2  9]
 [ 6  3  6]
 [15  2  3]
 [ 9 18 11]]


### column wise
concatenate((matrix1, matrix2), axis=1)

in order to concatenate, row has to be same for both the arrays

In [80]:
conCol = np.concatenate((con1, con2), axis=1)
print(conCol)

[[ 7  2  9 15  2  3]
 [ 6  3  6  9 18 11]]


## transpose matrix

In [85]:
tran = np.array([[1, 2, 3],
                     [4, 5, 6]])
transpose = tran.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


## splitting array

#### np.array_split(arr, no. of split)

In [87]:
array = np.random.randint(1, 10, size = (10,))
print(array)
splittedArray = np.array_split(array, 3)
print(splittedArray)

[8 4 1 4 8 6 9 5 2 9]
[array([8, 4, 1, 4]), array([8, 6, 9]), array([5, 2, 9])]


#### np.split(array, no. of split)
can only be used on arrays where equal divison can take place

In [96]:
arrSplit = np.random.randint(1, 10, size=(10,))
print(arrSplit)
splittedArray2 = np.split(arrSplit, 5)
print(splittedArray2)

[1 8 5 6 7 3 3 4 1 3]
[array([1, 8]), array([5, 6]), array([7, 3]), array([3, 4]), array([1, 3])]


## Arithmetic operator and mathematical functions

In [8]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 2, 3, 4, 5])
print(f"x: {x}")
print(f"y: {y}")

x: [1 2 3 4 5]
y: [1 2 3 4 5]


### addition, substraction, multiplication, division, mod

In [117]:
print(f"x + y : {x+y}")

print(f"x - y: {x-y}")

print(f"x * y: {x*y}")

print(f"x / y: {x/y}")

print(f"x % y: {x%y}")

x + y : [ 2  4  6  8 10]
x - y: [0 0 0 0 0]
x * y: [ 1  4  9 16 25]
x / y: [1. 1. 1. 1. 1.]
x % y: [0 0 0 0 0]


### trigonometry

In [118]:
sin_x = np.sin(x)
print(f"sin(x): {sin_x}")

cos_x = np.cos(x)
print(f"cos(x): {cos_x}")

tan_x = np.tan(x)
print(f"tan(x): {tan_x}")

sin(x): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
cos(x): [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
tan(x): [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


### radian to degree conversion

In [9]:
deg_conversion = np.rad2deg(x)
print(f"radian to degree conversion of x: {deg_conversion}")

radian to degree conversion of x: [ 57.29577951 114.59155903 171.88733854 229.18311805 286.47889757]


### degree to radian conversion

In [10]:
rad_conversion = np.deg2rad(deg_conversion)
print(f"degree to radian conversion: {rad_conversion}")

degree to radian conversion: [1. 2. 3. 4. 5.]


### log base 10

In [121]:
log_10 = np.log10(x)
print(f"log base 10 values of x: {log_10}")

log base 10 values of x: [0.         0.30103    0.47712125 0.60205999 0.69897   ]


### log base 2

In [122]:
log_2 = np.log2(x)
print(f"log base 2 values of x: {log_2}")

log base 2 values of x: [0.         1.         1.5849625  2.         2.32192809]


### square root

In [123]:
sqrt = np.sqrt(x)
print(f"square root of x: {sqrt}")

square root of x: [1.         1.41421356 1.73205081 2.         2.23606798]


### sum

In [124]:
sum = np.sum(x)
print(f"sum of x: {sum}")

sum of x: 15


### cumulative sum

In [125]:
cumulative = np.cumulative_sum(x)
print(f"cumulative sum of x: {cumulative}")

cumulative sum of x: [ 1  3  6 10 15]


## Broadcasting

In [129]:
pow2 = x ** 2
print(f"x**2: {pow2}")

sum2 = x + 2
print(f"x+2: {sum2}")

sub2 = x - 2
print(f"x-2: {sub2}")

mul2 = x * 2
print(f"x*2; {mul2}")

div2 = x / 2
print(f"x/2: {div2}")

mod2 = x % 2
print(f"x%2: {mod2}")

x**2: [ 1  4  9 16 25]
x+2: [3 4 5 6 7]
x-2: [-1  0  1  2  3]
x*2; [ 2  4  6  8 10]
x/2: [0.5 1.  1.5 2.  2.5]
x%2: [1 0 1 0 1]


In [131]:
# the row size has to be same for both the arrays in such addition

add1 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

add2 = np.array([1, 2, 3])

add = add1 + add2
print(add)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


## Logical Function

In [138]:
greater = x > y
print(greater)

lower = x < y
print(lower)

greater_equal = x >= y
print(greater_equal)

lower_equal = x <= y
print(lower_equal)

equal = x == y
print(equal)

notEql = x != y
print(notEql)

[False False False False False]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
[ True  True  True  True  True]
[False False False False False]


### all()
finds if all the elements within the array is true

In [139]:
print(np.all(greater_equal))

True


In [140]:
print(np.all(greater))

False


### any()
finds if any of the element within the array is true

In [141]:
print(np.any(greater))

False


In [142]:
print(np.any(greater_equal))

True


## sorting

In [143]:
unsorted = np.array([1, 0, 2, 9, 3, 8, 4, 7, 5, 6])

### inplace sorting

In [146]:
sortedInplace = unsorted.copy()
print(f"before sorting: {sortedInplace}")
sortedInplace.sort()
print(f"after sorting is applied: {sortedInplace}")

before sorting: [1 0 2 9 3 8 4 7 5 6]
after sorting is applied: [0 1 2 3 4 5 6 7 8 9]


### copy sorting

In [148]:
print(f"original array: {unsorted}")
sortedCopy = np.sort(unsorted)
print(f"applying copy sorting: {sortedCopy}")
print(f"original array: {unsorted}")

original array: [1 0 2 9 3 8 4 7 5 6]
applying copy sorting: [0 1 2 3 4 5 6 7 8 9]
original array: [1 0 2 9 3 8 4 7 5 6]


### 2d matrix

In [161]:
twoD = np.array([[8, 2, 4],
                [5, 7, 9], 
                [3, 6, 1]])

#### horizontal sort
axis=1

In [162]:
horizonSort = np.sort(twoD, axis=1)
print(horizonSort)

[[2 4 8]
 [5 7 9]
 [1 3 6]]


#### vertical sort
axis=0

In [163]:
verticalSort = np.sort(twoD, axis=0)
print(verticalSort)

[[3 2 1]
 [5 6 4]
 [8 7 9]]


## np.where(element to be searched)

will return the index val of the searched element

In [164]:
idx1 = np.where(x == 1)
print(idx1)

(array([0]),)


In [168]:
idx2 = np.where(x > 2)
print(idx2)

(array([2, 3, 4]),)


In [172]:
idx4 = np.where(twoD > 5)
print(idx4)

(array([0, 1, 1, 2]), array([0, 1, 2, 1]))


## np.where(condition, x, y)
if condition is true, keep x otherwise replace with y

will return the new array

In [169]:
idx3 = np.where(x > 2, x, 0)
print(idx3)

[0 0 3 4 5]


In [173]:
idx5 = np.where(twoD > 5, twoD, 0)
print(idx5)

[[8 0 0]
 [0 7 9]
 [0 6 0]]


## argmax()
returns the index of the max value in an array

In [175]:
print(x)
maxVal = np.argmax(x)
print(maxVal)

[1 2 3 4 5]
4


## argmin()
returns the index of the min value in an array

In [176]:
print(x)
minVal = np.argmin(x)
print(minVal)

[1 2 3 4 5]
0


## counting in ndarray

In [201]:
count = np.random.randint(1, 100, size=(100,))
print(count)

[57 16 25 75 49 59 71 44 37 16 37 41 57 72 70 78 51 67 12 13 21  6 31 27
 82 21 44 61 89 57 64 43 12 64 79 59  4 56 27 65 80 42 97 15 79 63 86 24
 71 98 53 66 30 14 98  5 49 85 35 80 27 51 57 60 13 33 94 66 91 81  2 92
 62 57 53 81 23 99 98 38 86 78 64 11 80 51 58 50 99 76 92 96 23 25 77 30
 20 72 30 28]


In [202]:
val_greaterThan_5 = np.count_nonzero(count > 50)
print(val_greaterThan_5)

58


In [203]:
val_equal_2 = np.count_nonzero(count == 20)
print(val_equal_2)

1


In [204]:
val_lessThan_50 = np.count_nonzero(count < 50)
print(val_lessThan_50)

41


## np.unique()
provides unique values from the given array

In [205]:
uniqueVal = np.unique(count, return_counts=True)
print(uniqueVal)

(array([ 2,  4,  5,  6, 11, 12, 13, 14, 15, 16, 20, 21, 23, 24, 25, 27, 28,
       30, 31, 33, 35, 37, 38, 41, 42, 43, 44, 49, 50, 51, 53, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 70, 71, 72, 75, 76, 77, 78, 79,
       80, 81, 82, 85, 86, 89, 91, 92, 94, 96, 97, 98, 99]), array([1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 3, 1, 3, 1, 1, 1, 2,
       1, 1, 1, 1, 2, 2, 1, 3, 2, 1, 5, 1, 2, 1, 1, 1, 1, 3, 1, 2, 1, 1,
       2, 2, 1, 1, 1, 2, 2, 3, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 3, 2]))


In [206]:
# value unpacking since it returns an array
uniqueVal, count = np.unique(count, return_counts=True)
print(uniqueVal)
print(count)

[ 2  4  5  6 11 12 13 14 15 16 20 21 23 24 25 27 28 30 31 33 35 37 38 41
 42 43 44 49 50 51 53 56 57 58 59 60 61 62 63 64 65 66 67 70 71 72 75 76
 77 78 79 80 81 82 85 86 89 91 92 94 96 97 98 99]
[1 1 1 1 1 2 2 1 1 2 1 2 2 1 2 3 1 3 1 1 1 2 1 1 1 1 2 2 1 3 2 1 5 1 2 1 1
 1 1 3 1 2 1 1 2 2 1 1 1 2 2 3 2 1 1 2 1 1 2 1 1 1 3 2]


## Statistical Analysis

### Data Load

In [209]:
data = np.genfromtxt("marks.csv", delimiter=",", skip_header=1)
print(data)

[[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8.   9.]
 [ 10.  11.  12.]
 [ 13.  14.  15.]
 [ 16.  17.  18.]
 [ 19.  20.  21.]
 [ 22.  23.  24.]
 [ 25.  26.  27.]
 [ 28.  29.  30.]
 [ 31.  32.  34.]
 [ 35.  36.  37.]
 [ 38.  39.  40.]
 [ 41.  42.  43.]
 [ 44.  45.  46.]
 [ 47.  48.  49.]
 [ 50.  51.  52.]
 [ 53.  54.  55.]
 [ 56.  57.  58.]
 [ 59.  60.  61.]
 [ 62.  63.  64.]
 [ 65.  66.  67.]
 [ 68.  69.  70.]
 [ 71.  72.  73.]
 [ 74.  75.  76.]
 [ 77.  78.  79.]
 [ 80.  81.  82.]
 [ 83.  84.  85.]
 [ 86.  87.  88.]
 [ 89.  90.  91.]
 [ 92.  93.  94.]
 [ 95.  96.  97.]
 [ 98.  99. 100.]]


### math marks

In [211]:
mat = data[::, :1]
print(mat)

[[ 1.]
 [ 4.]
 [ 7.]
 [10.]
 [13.]
 [16.]
 [19.]
 [22.]
 [25.]
 [28.]
 [31.]
 [35.]
 [38.]
 [41.]
 [44.]
 [47.]
 [50.]
 [53.]
 [56.]
 [59.]
 [62.]
 [65.]
 [68.]
 [71.]
 [74.]
 [77.]
 [80.]
 [83.]
 [86.]
 [89.]
 [92.]
 [95.]
 [98.]]


In [212]:
print(mat.T)

[[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28. 31. 35. 38. 41. 44. 47. 50. 53.
  56. 59. 62. 65. 68. 71. 74. 77. 80. 83. 86. 89. 92. 95. 98.]]


### finding max math marks

In [214]:
matMax = np.max(mat)
print(matMax)

98.0


### finding min math marks

In [215]:
minMath = np.min(mat)
print(minMath)

1.0


### finding average math marks

In [216]:
avgMath = np.mean(mat)
print(avgMath)

49.666666666666664


### finding median math marks

In [217]:
medianMath = np.median(mat)
print(medianMath)

50.0


### finding standard deviation
the more large standard deviation is, the more scattered the data are

In [218]:
sdMath = np.std(mat)
print(sdMath)

28.95206766747795


## correlation coefficient

In [226]:
studyHours = np.array([1, 2, 3, 4, 5])
examScores = np.array([60, 70, 80, 90, 100])
data = np.array([studyHours, 
                 examScores])
print(data)

[[  1   2   3   4   5]
 [ 60  70  80  90 100]]


In [227]:
correlation = np.corrcoef(data)
print(correlation)

[[1. 1.]
 [1. 1.]]


## Linear Algebra

In [229]:
matrix1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

matrix2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

### matrix multiplication

In [230]:
dotProduct = np.dot(matrix1, matrix2)
print(dotProduct)

[[ 58  64]
 [139 154]]


### trace matrix
summation of the diagonal elements

In [231]:
trace = np.trace(matrix1)
print(trace)

6


### determinent of a matrix

In [234]:
matrix3 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

det = np.linalg.det(matrix3)
print(det)

0.0


### rank of a matrix

In [233]:
rank = np.linalg.matrix_rank(matrix3)
print(rank) 

2


# Pandas

In [2]:
import pandas as pd

## Different file loading

### csv file

In [14]:
df = pd.read_csv("student_data.csv")
print(df, type(df))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0   
1     PH1002     Fatima Akhter                  92.0             92.0   
2     PH1003     Imran Hossain                  88.0             88.0   
3     PH1004  Jannatul Ferdous                  78.0             78.0   
4     PH1005       Kamal Uddin                   NaN              NaN   
5     PH1006       Laila Begum                  75.0             75.0   
6     PH1007    Mahmudul Hasan                  80.0             80.0   
7     PH1008       Nadia Islam                  81.0             81.0   
8     PH1009        Omar Faruq                  72.0             72.0   
9     PH1010      Priya Sharma                  89.0             89.0   
10    PH1011      Rahim Sheikh                   NaN              NaN   
11    PH1012   Sadia Chowdhury                  85.0             85.0   
12    PH1013      Tanvir Ahmed                  75.

In [9]:
student_id = df["StudentID"]
print(student_id, type(student_id))

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: object <class 'pandas.core.series.Series'>


### excel file

In [13]:
df_xlsx = pd.read_excel('student_marks.xlsx')
print(df_xlsx, type(df_xlsx))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0   
1     PH1002     Fatima Akhter                  92.0             92.0   
2     PH1003     Imran Hossain                  88.0             88.0   
3     PH1004  Jannatul Ferdous                  78.0             78.0   
4     PH1005       Kamal Uddin                   NaN              NaN   
5     PH1006       Laila Begum                  75.0             75.0   
6     PH1007    Mahmudul Hasan                  80.0             80.0   
7     PH1008       Nadia Islam                  81.0             81.0   
8     PH1009        Omar Faruq                  72.0             72.0   
9     PH1010      Priya Sharma                  89.0             89.0   
10    PH1011      Rahim Sheikh                   NaN              NaN   
11    PH1012   Sadia Chowdhury                  85.0             85.0   
12    PH1013      Tanvir Ahmed                  75.

In [3]:
import pyarrow

### parquet file

In [4]:
df_parquet = pd.read_parquet('student_marks.parquet')
print(df_parquet, type(df_parquet))

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0   
1     PH1002     Fatima Akhter                  92.0             92.0   
2     PH1003     Imran Hossain                  88.0             88.0   
3     PH1004  Jannatul Ferdous                  78.0             78.0   
4     PH1005       Kamal Uddin                   NaN              NaN   
5     PH1006       Laila Begum                  75.0             75.0   
6     PH1007    Mahmudul Hasan                  80.0             80.0   
7     PH1008       Nadia Islam                  81.0             81.0   
8     PH1009        Omar Faruq                  72.0             72.0   
9     PH1010      Priya Sharma                  89.0             89.0   
10    PH1011      Rahim Sheikh                   NaN              NaN   
11    PH1012   Sadia Chowdhury                  85.0             85.0   
12    PH1013      Tanvir Ahmed                  75.

### json file

In [7]:
df_json = pd.read_json('student_marks.json')
print(df_json, type(df_json))

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                    85               85   
1    PH1002     Fatima Akhter                    92               92   
2    PH1004  Jannatul Ferdous                    78               78   

   Python Marks  
0            88  
1            90  
2            82   <class 'pandas.core.frame.DataFrame'>


## df

In [15]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet


### head()
shows the first 5 rows of the data frame if no parameter is passed
so by default, the parameter is 5

In [17]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram


In [19]:
df.head(9)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka


### tail()
by default shows the last 5 rows if no parameter is passed

In [20]:
df.tail()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka


In [22]:
df.tail(2)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka


### columns
attribute of the df class

In [33]:
df.columns

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='object')

In [43]:
col = list(df.columns)
print(col, type(col))

['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location'] <class 'list'>


In [44]:
col2 = np.array(df.columns)
print(col2, col2.dtype)

['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location'] object


### index
this is the attribute of the df class which shows the range of the startign to ending_index+1 of the data frame

In [45]:
df.index

RangeIndex(start=0, stop=20, step=1)

In [47]:
idx = np.array(df.index)
print(idx, idx.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] int64


### info()
shows info regarding df

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   StudentID             20 non-null     object 
 1   FullName              20 non-null     object 
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object 
 6   EnrollmentDate        20 non-null     object 
 7   Instructor            20 non-null     object 
 8   Location              20 non-null     object 
dtypes: float64(3), object(6)
memory usage: 1.5+ KB


### sample()
by default shows only 1 sample data randomly (if no parameter is passed)

In [52]:
df.sample()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka


In [51]:
df.sample(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna


### statistical values

#### describe()

In [53]:
df.describe()

,Data Structure Marks,Algorithm Marks,Python Marks
count,16.000000,16.000000,15.000000
mean,84.000000,84.000000,85.666667
std,6.501282,6.501282,5.394000
min,72.000000,72.000000,76.000000
25%,79.500000,79.500000,83.000000
50%,85.500000,85.500000,85.000000
75%,88.250000,88.250000,88.500000
max,94.000000,94.000000,95.000000


## Transforming to data frame from inbuilt datas

### list

In [54]:
lst = [["Alice", 25],
       ["Bob", 30],
       ["Charlie", 28]]

In [69]:
list_df = pd.DataFrame(lst, columns=["Name", "Age"],index=[1, 2, 3])
print(list_df)
print()
print(type(list_df))
print()
print(list_df.dtypes)

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object


In [70]:
list_df

,Name,Age
1,Alice,25
2,Bob,30
3,Charlie,28


### tuple

In [71]:
tup = (("Alice", 25),
       ("Bob", 30),
       ("Charlie", 28))

In [72]:
tup_df = pd.DataFrame(tup, columns=["Name", "Age"], index=[1,2,3])
print(tup_df)
print()
print(type(tup_df))
print()
print(tup_df.dtypes)

      Name  Age
1    Alice   25
2      Bob   30
3  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object


In [73]:
tup_df

,Name,Age
1,Alice,25
2,Bob,30
3,Charlie,28


### dictionary

In [76]:
dic = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
}

In [82]:
dic_df = pd.DataFrame(dic)
print(dic_df)
print()
print(type(dic_df))
print()
print(dic_df.dtypes)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
dtype: object


In [83]:
dic_df

,Name,Age
0,Alice,25
1,Bob,30
2,Charlie,28


### dictionary within a list

In [86]:
l = [
    {"Name": "Alice", "Age": 25, "City": "New York"},
    {"Name": "Bob", "Age": 30, "City": "New York"},
    {"Name": "Charlie", "Age": 28},
]

In [89]:
l_df = pd.DataFrame(l)
print(l_df)
print()
print(type(l_df))
print()
print(l_df.dtypes)

      Name  Age      City
0    Alice   25  New York
1      Bob   30  New York
2  Charlie   28       NaN

<class 'pandas.core.frame.DataFrame'>

Name    object
Age      int64
City    object
dtype: object


In [90]:
l_df

,Name,Age,City
0,Alice,25,New York
1,Bob,30,New York
2,Charlie,28,NaN


## Accessing values from data frame

###