In [1]:
!pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter #Counts frequency of elements in a list or text.
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize  #Splits text into individual words/tokens.
import nltk # Used for NLP tasks like tokenization, stemming, stopword removal, etc

In [3]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""

In [4]:
# NLTK does NOT come with pretrained tokenizers by default.

# Tokenization
nltk.download('punkt')

# Some newer NLTK versions require additional tokenizer tables.
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /home/safir/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/safir/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

# Tokenize

In [5]:
tokens = word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

# Build vocabs

In [6]:
#build vocab
vocab = { '<unk>' : 0 }

In [7]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token]= len(vocab)

vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [8]:
len(vocab)

284

# Extract sentence from data

In [9]:
input_sentences = document.split('\n')

In [10]:
input_sentences[3]

'The station was nearly empty except for a few passengers waiting quietly on wooden benches.'

In [11]:
def text_to_indices(sentence,vocab):
  numerical_sentence = []
  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [12]:
input_numerical_sentence= []
for sentence in input_sentences:
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))

In [13]:
input_numerical_sentence

[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

# training Sequence form

In [14]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [15]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [16]:
len(training_sequence)

555

In [17]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [1, 2, 3, 4], [5, 6], [5, 6, 7]]

In [18]:
len_list = []
for sequence in training_sequence:
  len_list.append(len(sequence))

In [19]:
max(len_list)

25

# Padding

In [20]:
#logic
[0]* (max(len_list)-len(sequence))

[]

In [21]:
padded_training_sequence = []
for sequence in training_sequence:
  padded_training_sequence.append( [0]* (max(len_list)-len(sequence)) + sequence  )


In [22]:
len(padded_training_sequence[0])

25

In [23]:
padded_training_sequence[0]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]

In [24]:
padded_training_sequence[6]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 6, 7, 8, 9]

# tensor convert


In [25]:
padded_training_sequence = torch.tensor(padded_training_sequence,dtype=torch.long)

In [26]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

In [27]:
X = padded_training_sequence[:, :-1]

In [28]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0, 158,  ...,   2,   3,  40],
        [  0, 158, 223,  ...,   3,  40,   1],
        [158, 223,  10,  ...,  40,   1,  41]])

In [29]:
y = padded_training_sequence[:,-1]

In [30]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

In [31]:
len(X)

555

In [32]:
len(y)

555

# Custom Dataset and Dataloader

In [33]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx) :
    return self.X[idx], self.y[idx]

In [34]:
dataset = CustomDataset(X,y)

In [35]:
len(dataset)

555

In [36]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [37]:
for input , output in dataloader:
  print(input,output)





tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   1,  53,  54,  55,  56],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  62,
         259,  22,   6, 260,  40,   1, 168, 169, 261,  56],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   1,   7,  37,  10, 272, 253],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 125, 126],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,  28],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0, 219,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   6,  33,  34,  35,  36,
           1,  37,  38,   1,  39,   3,  40,   1,  41,  42],
        [  0,   0,   0,   0

In [38]:
X.shape

torch.Size([555, 24])

In [39]:
y.shape

torch.Size([555])

In [40]:
X[0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [41]:
X[554]

tensor([158, 223,  10,  11, 278, 281, 282, 139, 283,   8,   4,  50,   1, 172,
        171, 131, 153,   5,   1,   2,   3,  40,   1,  41])

In [42]:
# X[555]

In [43]:
len(dataset)

555

In [44]:
len(vocab)

284

In [45]:
len(dataset[0])

2

In [46]:
len(dataset[0][0])

24

In [47]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [48]:
import torch
import torch.nn as nn
class LSTMModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=100)
        self.lstm = nn.LSTM(input_size=100, hidden_size=150, batch_first=True)
        self.fc = nn.Linear(in_features=150, out_features=vocab_size)
    def forward(self, X):
        embedded = self.embedding(X)
        intermediate_hidden_state, (final_hidden_state, final_cell_state) = self.lstm(embedded)
        output = self.fc(final_hidden_state.squeeze(0))
        return output

model = LSTMModel(len(vocab))
device = ("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [49]:
dataset[0][0].unsqueeze(0)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [50]:
a = nn.Embedding(num_embeddings=len(vocab), embedding_dim=100)
b = nn.LSTM(100, 150, batch_first=True)
c = nn.Linear(150, len(vocab))
# a(dataset[0][0].unsqueeze(0))
# b(a(dataset[0][0].unsqueeze(0)))

In [51]:
intermediate_hidden_state, (final_hidden_state, final_cell_state) = b(a(dataset[0][0].unsqueeze(0)))

In [52]:
final_hidden_state.squeeze(0)

tensor([[-0.0635,  0.1102,  0.0080, -0.0292, -0.1832,  0.1575, -0.0242, -0.0356,
         -0.0012,  0.1088, -0.2863,  0.0939,  0.0181,  0.1973, -0.1292,  0.2389,
          0.2429, -0.0312, -0.0755,  0.1172, -0.1671,  0.1872,  0.0535, -0.0093,
          0.1252, -0.1424,  0.1999, -0.2145,  0.0827, -0.1216, -0.2137, -0.1237,
          0.1527,  0.0572, -0.0301,  0.0681,  0.0740,  0.1210,  0.0544, -0.0391,
          0.0497, -0.0831,  0.0063, -0.0246,  0.1697, -0.0321, -0.0065,  0.1285,
         -0.0145, -0.1724, -0.1085,  0.1957, -0.0238, -0.1066, -0.1052, -0.0605,
          0.2509, -0.0281, -0.0439, -0.1285, -0.0254, -0.1402, -0.0006,  0.0303,
         -0.1219, -0.2579, -0.0384, -0.1331,  0.0670,  0.1354, -0.1778, -0.0021,
         -0.3383,  0.0040, -0.1783, -0.0124,  0.3204, -0.0116,  0.1137, -0.0532,
         -0.1746, -0.1315,  0.2197, -0.1606,  0.1309,  0.0892, -0.1171,  0.1068,
          0.1737,  0.2203, -0.0014,  0.1786, -0.0145, -0.0597, -0.1859, -0.0219,
         -0.0321, -0.0515, -

In [53]:
c(final_hidden_state.squeeze(0)).shape

torch.Size([1, 284])

# LSTM Cell

In [54]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    self.lstm = nn.LSTM(100,150,batch_first=True)
    self.fc = nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded = self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [55]:
model = LSTMModel(len(vocab))

In [56]:
model = LSTMModel(len(vocab))

In [57]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [58]:
device

device(type='cpu')

In [59]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [60]:
len(vocab)

284

In [61]:
x = nn.Embedding(284,100)
y = nn.LSTM(100,150,batch_first=True)
z = nn.Linear(150, 284)

In [62]:
len(dataset)

555

In [63]:
dataset[0][0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [64]:
dataset[0][0].shape

torch.Size([24])

In [65]:
dataset[0][0].unsqueeze(0).shape

torch.Size([1, 24])

In [66]:
a = dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [67]:
x(a)

tensor([[[ 0.6715, -0.3957, -0.1172,  ..., -0.1088,  1.4601,  1.6185],
         [ 0.6715, -0.3957, -0.1172,  ..., -0.1088,  1.4601,  1.6185],
         [ 0.6715, -0.3957, -0.1172,  ..., -0.1088,  1.4601,  1.6185],
         ...,
         [ 0.6715, -0.3957, -0.1172,  ..., -0.1088,  1.4601,  1.6185],
         [ 0.6715, -0.3957, -0.1172,  ..., -0.1088,  1.4601,  1.6185],
         [ 1.2336,  0.9360, -1.4628,  ...,  1.2674, -1.7509,  0.2217]]],
       grad_fn=<EmbeddingBackward0>)

In [68]:
x(a).shape

torch.Size([1, 24, 100])

In [69]:
b = x(a)

In [70]:
a, b = y(x(dataset[0][0].unsqueeze(0)))

In [71]:
intermediate_hidden_state, (final_hidden_state, final_cell_state) = y(x(dataset[0][0].unsqueeze(0)))

In [72]:
len(y(b))

AttributeError: 'tuple' object has no attribute 'dim'

In [ ]:
c, d = y(x(a))

RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.FloatTensor instead (while checking arguments for embedding)

In [ ]:
c ,d = y(b)

: 

In [ ]:
c.shape  #Set of all intermediate hidden state

torch.Size([1, 24, 150])

: 

In [ ]:
len(y(b))

2

: 

In [ ]:
len(d)

2

: 

In [ ]:
e, f = d


: 

In [ ]:
e.shape  #Cell state

torch.Size([1, 1, 150])

: 

In [ ]:
f.shape

torch.Size([1, 1, 150])

: 

In [ ]:
f_temp = f.squeeze(0).shape
f_temp

torch.Size([1, 150])

: 

In [ ]:
f_temp = f.squeeze(0)

: 

In [ ]:
z(f_temp)

tensor([[-1.0288e-01,  9.0241e-02, -3.6744e-01, -1.8606e-01,  2.1439e-01,
         -3.7909e-01,  6.6288e-02,  1.0564e-01, -4.4224e-02, -3.5619e-02,
          1.9431e-02, -3.2249e-01,  2.1312e-01,  1.4011e-02,  1.7418e-01,
          9.4035e-02,  1.4253e-01, -3.9195e-02,  1.8830e-01,  1.9060e-01,
          1.6167e-01, -4.2534e-02,  7.7963e-02, -1.9106e-01,  4.3260e-02,
         -1.1887e-01, -4.2527e-02,  1.4716e-02,  3.0948e-02, -3.1270e-01,
         -2.1235e-01,  3.1122e-01, -6.9166e-02,  1.2211e-03, -1.6402e-01,
         -7.0305e-02, -4.5092e-02,  1.7574e-01,  2.9356e-02, -2.0731e-01,
          1.1756e-01, -2.9336e-02, -3.6268e-01, -1.0837e-01, -1.8156e-03,
          2.8497e-01,  2.9194e-01,  1.6879e-01,  2.5855e-01, -1.2502e-01,
          6.1689e-02, -1.5951e-01,  2.8499e-01,  4.9471e-03, -2.9312e-01,
         -3.1729e-01, -2.9154e-01,  9.3037e-02, -2.1439e-01,  3.1389e-01,
         -1.4153e-01, -9.7046e-02,  1.6147e-01, -1.7290e-01,  2.1467e-01,
         -1.3293e-02, -3.3280e-01,  1.

: 

In [ ]:
len(f_temp[0])

150

: 

In [ ]:
len(z(f_temp)[0])

284

: 

In [ ]:
len(vocab)

284

: 

In [ ]:
for batch_x , batch_y in dataloader:
  print(batch_x, batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   1,   7,  37,  10, 272, 253,  10],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,  11,  50, 153, 170],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,  98,   1,  99, 100, 101,
         102, 103, 104, 101,  14, 105,  56,   6, 106, 107],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  11,
         116,   6, 117, 118, 119, 120, 121, 122, 123,   6],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   1,  16,  22,  18, 243, 244],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,  11,  50, 153, 170, 232, 148],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   1,  53,  54,  55,  56,   6,  57],
        [  0,   0,   0,   0

# Training loop

In [73]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)


# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 100.7102
Epoch: 2, Loss: 94.7248
Epoch: 3, Loss: 87.3017
Epoch: 4, Loss: 81.5795
Epoch: 5, Loss: 76.0700
Epoch: 6, Loss: 70.6103
Epoch: 7, Loss: 64.7162
Epoch: 8, Loss: 58.9346
Epoch: 9, Loss: 53.3992
Epoch: 10, Loss: 48.2467
Epoch: 11, Loss: 43.1328
Epoch: 12, Loss: 39.2108
Epoch: 13, Loss: 34.2582
Epoch: 14, Loss: 30.2178
Epoch: 15, Loss: 26.9396
Epoch: 16, Loss: 23.4772
Epoch: 17, Loss: 21.1143
Epoch: 18, Loss: 18.3854
Epoch: 19, Loss: 16.3302
Epoch: 20, Loss: 14.5100
Epoch: 21, Loss: 13.2307
Epoch: 22, Loss: 11.9613
Epoch: 23, Loss: 10.6047
Epoch: 24, Loss: 9.5377
Epoch: 25, Loss: 8.6749
Epoch: 26, Loss: 7.8444
Epoch: 27, Loss: 7.2170
Epoch: 28, Loss: 6.6580
Epoch: 29, Loss: 6.1276
Epoch: 30, Loss: 5.8702
Epoch: 31, Loss: 5.6909
Epoch: 32, Loss: 5.1802
Epoch: 33, Loss: 4.8133
Epoch: 34, Loss: 4.5225
Epoch: 35, Loss: 4.2649
Epoch: 36, Loss: 4.1706
Epoch: 37, Loss: 4.0541
Epoch: 38, Loss: 3.8730
Epoch: 39, Loss: 3.5820
Epoch: 40, Loss: 3.3882
Epoch: 41, Loss: 3.4836
E

# Prediction

In [74]:
max(len_list)

25

In [76]:
#logic
[0]* (25-len(numerical_text)) + numerical_text

NameError: name 'numerical_text' is not defined

In [78]:
def prediction(model,vocab,text):

  #tokenize
  tokenized_text = word_tokenize(text.lower())

  # print(tokenized_text)


  #numerical indices
  numerical_text = text_to_indices(tokenized_text,vocab)

  # print(numerical_text)

  #padding
  padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)

  # print(padded_text)

  # print(len(padded_text))

  # print(padded_text.shape)


  #send to model
  output = model(padded_text)

  # print("model's output",output)

  # print("printing total_elements",len(output[0]))

  #predicted index

  value, index = torch.max(output,dim=1)

  # print(f"printing value and index {value}, {index}")

  # print(f"printing  index  {index}")

  # print("printing the word ")

  # print(list(vocab.keys())[index])

  #merge with text

  return text + " " + list(vocab.keys())[index]





In [79]:
prediction(model,vocab,"Hi how are you the station was")

'Hi how are you the station was small'

In [80]:
len(vocab)

284

In [81]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

# Generate Automatically

In [82]:
import time
num_tokens = 20
input_text= 'Daniel checked the ticket'

for i in range(num_tokens):
  output_text = prediction(model,vocab,input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . . .

# Accuracy calculation

In [83]:
def calculate_accuracy(model,dataloader,device):

  model.eval() #set the model to evaluation mode

  correct = 0
  total = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:
      # print(len(batch_x)),len(batch_y)
      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      #get model prediction
      output = model(batch_x)

      # print(len(output[0]))

      #get the predictec word indices

      _, predicted = torch.max(output,dim=1)

      # print("printing predicted",predicted)

      #compare wityh actual label

      # print("printing y lable",batch_y)

      # print(predicted == batch_y)
      correct += (predicted == batch_y).sum().item()

      # print(correct)
      # print("working with total",batch_y.size())
      total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

In [84]:
accuracy = calculate_accuracy(model,dataloader,device)

print(f" Model accuracy {accuracy :.2f}%")

 Model accuracy 96.94%
