In [1]:
import numpy as np

### 🧊 Task: Convert Celsius to Fahrenheit
```py
celcius = [0, 10, 20, 30, 40]
```
You have a list of temperatures recorded in Celsius. Your task is to:
   
- Create a NumPy array from the given list. 
- Convert all temperatures from Celsius to Fahrenheit. The formula is:  
F = C * 1.8 + 32
- Print the new Fahrenheit array.


In [5]:
celcius = [0, 10, 20, 30, 40]

celciusNumpy = np.array(celcius)
print(celciusNumpy, type(celciusNumpy))

farenhiteNumpy = celciusNumpy * 1.8 + 32
print(farenhiteNumpy)

[ 0 10 20 30 40] <class 'numpy.ndarray'>
[ 32.  50.  68.  86. 104.]


### ⏱️ Task: Analyze Athlete's Lap Times

```python
lap_times = [75, 80, 78, 82, 77]
```
You have a Python list containing the lap times (in seconds) for an athlete.

**Task:**

- Convert the list into a NumPy array.  
- Print the array's shape, size, and data type.  
- The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.  
- Print the new array of lap times in minutes.


In [13]:
lap_times = [75, 80, 78, 82, 77]

lapTimesNumPyArr = np.array(lap_times)
print(lapTimesNumPyArr, type(lapTimesNumPyArr))

print(f"shape: {lapTimesNumPyArr.shape}")
print(f"size: {lapTimesNumPyArr.size}")
print(f"Data Type: {lapTimesNumPyArr.dtype}")

lapTimesNumPyArrPerMin = lapTimesNumPyArr/60
print(f"lap times in minutes: {lapTimesNumPyArrPerMin}")

[75 80 78 82 77] <class 'numpy.ndarray'>
shape: (5,)
size: 5
Data Type: int64
lap times in minutes: [1.25       1.33333333 1.3        1.36666667 1.28333333]
