In [4]:
import torch
print(torch.__version__)

2.10.0+cu128


In [5]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Device Name {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")  

GPU is not available


# Creating Tensors

In [6]:
a = torch.empty(2, 3)
a

tensor([[1.7466e+19, 4.2330e+21, 4.1576e+21],
        [7.5020e+28, 1.6460e+19, 8.1446e-33]])

In [9]:
print(type(a))

<class 'torch.Tensor'>


In [10]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(2, 3)

tensor([[0.6873, 0.1078, 0.7530],
        [0.2783, 0.8628, 0.2999]])

In [16]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
torch.tensor([
    [1, 2, 3], 
    [4, 5, 6]
])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [20]:
torch.arange(1, 10, 1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.linspace(1, 100, 10)

tensor([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

# Tensors shape

In [24]:
x = torch.tensor([
    [1, 2, 3], 
    [4, 5, 6]
])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
x.shape

torch.Size([2, 3])

In [26]:
torch.empty_like(x)

tensor([[      392134656,               0, 137563507523584],
        [             97,       393808112,       385479248]])

In [27]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [36]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data Types

In [38]:
x.dtype

torch.int64

In [40]:
torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0], dtype=torch.int32)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [42]:
torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)

tensor([1., 2., 3., 4., 5.])

In [43]:
b = x.to(torch.float32)
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [46]:
b.dtype

torch.float32

# Mathematical Operations

In [47]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [48]:
x + 2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [49]:
x - 2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [50]:
x * 2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [51]:
x / 2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [52]:
# taking floor values
x // 2

tensor([[0, 1, 1],
        [2, 2, 3]])

In [53]:
x ** 2

tensor([[ 1,  4,  9],
        [16, 25, 36]])

In [54]:
x % 2

tensor([[1, 0, 1],
        [0, 1, 0]])

# Element wise operation

In [57]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

In [59]:
a + b

tensor([[0.9357, 1.0899, 0.5967],
        [1.7253, 1.5526, 1.7335]])

In [60]:
a - b

tensor([[ 0.4879,  0.4852,  0.2399],
        [ 0.0776,  0.4411, -0.2205]])

In [61]:
a * b

tensor([[0.1594, 0.2381, 0.0746],
        [0.7426, 0.5540, 0.7391]])

In [62]:
a / b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [63]:
a**b

tensor([[0.9267, 0.9303, 0.8560],
        [0.9180, 0.9983, 0.7614]])

In [64]:
a % b

tensor([[0.0401, 0.1829, 0.0615],
        [0.0776, 0.4411, 0.7565]])

In [65]:
c = torch.tensor([-1, -2, -3, -4, -5])
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [66]:
torch.negative(x)

tensor([[-1, -2, -3],
        [-4, -5, -6]])

In [70]:
c = torch.tensor([1.2, 2.3, 3.4, 4.5, 5.6, 6.7])
torch.round(c)

tensor([1., 2., 3., 4., 6., 7.])

In [72]:
torch.floor(c)

tensor([1., 2., 3., 4., 5., 6.])

In [73]:
torch.ceil(c)

tensor([2., 3., 4., 5., 6., 7.])

In [74]:
torch.clamp(c, 2, 5)

tensor([2.0000, 2.3000, 3.4000, 4.5000, 5.0000, 5.0000])

# Reduction Operation

In [75]:
d = torch.randint(size=(3, 3), low=2, high=8, dtype=torch.float32)
d

tensor([[6., 5., 5.],
        [5., 2., 6.],
        [3., 4., 2.]])

In [77]:
torch.sum(d)

tensor(38.)

In [78]:
d

tensor([[6., 5., 5.],
        [5., 2., 6.],
        [3., 4., 2.]])

In [79]:
torch.sum(d, dim=0)

tensor([14., 11., 13.])

In [81]:
torch.sum(d, dim=1)

tensor([16., 13.,  9.])

In [76]:
torch.mean(d)

tensor(4.2222)

In [82]:
torch.mean(d, dim=0)

tensor([4.6667, 3.6667, 4.3333])

In [83]:
torch.mean(d, dim=1)

tensor([5.3333, 4.3333, 3.0000])

In [84]:
torch.median(d)

tensor(5.)

In [86]:
torch.max(d)

tensor(6.)

In [87]:
torch.min(d)

tensor(2.)

In [88]:
torch.prod(d)

tensor(216000.)

In [89]:
torch.std(d)

tensor(1.5635)

In [90]:
torch.var(d)

tensor(2.4444)

In [91]:
torch.argmax(d)
# returns index of the max value

tensor(0)

In [92]:
# returns index of the min value
torch.argmin(d)

tensor(4)

# Matrix Operations

In [95]:
e = torch.randint(size=(2, 3), low=0, high=10)
e

tensor([[9, 2, 6],
        [7, 7, 8]])

In [98]:
f = torch.randint(size=(3, 2), low=0, high=10)
f

tensor([[4, 3],
        [8, 8],
        [3, 3]])

In [99]:
torch.matmul(e, f)

tensor([[ 70,  61],
        [108, 101]])

In [100]:
# dot product
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
torch.dot(vector1, vector2)

tensor(11)

In [101]:
e

tensor([[9, 2, 6],
        [7, 7, 8]])

In [102]:
e.shape

torch.Size([2, 3])

In [105]:
torch.transpose(e, 0, 1)

tensor([[9, 7],
        [2, 7],
        [6, 8]])

In [106]:
g = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
g

tensor([[5., 0., 6.],
        [4., 0., 8.],
        [4., 7., 2.]])

In [107]:
# determinent
torch.det(g)

tensor(-112.0000)

In [108]:
torch.inverse(g)

tensor([[ 0.5000, -0.3750,  0.0000],
        [-0.2143,  0.1250,  0.1429],
        [-0.2500,  0.3125,  0.0000]])

# Comparison Operators

In [111]:
h = torch.randint(size=(2, 3), low=0, high=10)
i = torch.randint(size=(2, 3), low=0, high=10)

In [112]:
h

tensor([[1, 5, 4],
        [4, 1, 1]])

In [113]:
i

tensor([[2, 4, 7],
        [2, 5, 6]])

In [114]:
h > i

tensor([[False,  True, False],
        [ True, False, False]])

In [115]:
h < i

tensor([[ True, False,  True],
        [False,  True,  True]])

In [116]:
h == i

tensor([[False, False, False],
        [False, False, False]])

In [117]:
h != i

tensor([[True, True, True],
        [True, True, True]])

# Special Function

In [125]:
j = torch.tensor([0.001, 10, 20, 30])

In [126]:
torch.log(j)

tensor([-6.9078,  2.3026,  2.9957,  3.4012])

In [127]:
torch.exp(j)

tensor([1.0010e+00, 2.2026e+04, 4.8517e+08, 1.0686e+13])

In [128]:
torch.sqrt(j)

tensor([0.0316, 3.1623, 4.4721, 5.4772])

In [129]:
torch.sigmoid(j)

tensor([0.5002, 1.0000, 1.0000, 1.0000])

In [132]:
torch.softmax(j, dim=0)

tensor([9.3666e-14, 2.0611e-09, 4.5398e-05, 9.9995e-01])

In [133]:
torch.relu(j)

tensor([1.0000e-03, 1.0000e+01, 2.0000e+01, 3.0000e+01])

# Inplace Operations

In [135]:
k = torch.rand(2, 3)
l = torch.rand(2, 3)

In [136]:
k

tensor([[0.5224, 0.4175, 0.0340],
        [0.9157, 0.3079, 0.6269]])

In [137]:
k.add_(l)

tensor([[1.3501, 1.0769, 0.1227],
        [1.4047, 0.8966, 1.3610]])

In [138]:
k

tensor([[1.3501, 1.0769, 0.1227],
        [1.4047, 0.8966, 1.3610]])

In [144]:
l

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [148]:
torch.relu_(l)

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [150]:
l.relu_()

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [149]:
l

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

# Copying a tensor

In [152]:
m = l.clone()
m

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [153]:
m[0][0] = 1
m

tensor([[1.0000, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [154]:
l

tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])

In [157]:
# getting memory address
id(m)

137566950160208