# version 1

In [ ]:
import torch
import torch.nn as nn
# torch.nn is a module 
# torch is the main pytorch package

In [26]:
!pip install torchinfo

In [27]:
from torchinfo import summary

In [ ]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     self.linear = nn.Linear(num_features,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear(features)
#     out = self.sigmoid(out)()

#     return out

# Version 2

In [20]:
import torch
import torch.nn as nn

In [ ]:
# class Model(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()

#     #layer 1

#     self.linear1 = nn.Linear(num_features,3)  # Linear is a class within the nn module
#     self.relu = nn.ReLU()

#     #layer 2
#     self.linear2 = nn.Linear(3,1)
#     self.sigmoid = nn.Sigmoid()


#   def forward(self,features):
#     out = self.linear1(features)  # within __call__() theres a method called forward which takes the input feature
#     out = self.relu(out)

#     out = self.linear2(out)
#     out = self.sigmoid(out)

#     return out

In [22]:
features = torch.rand(10, 5)
features

tensor([[0.7954, 0.8236, 0.3686, 0.1309, 0.0383],
        [0.0281, 0.2348, 0.9708, 0.9580, 0.0911],
        [0.3567, 0.9422, 0.5143, 0.2614, 0.9415],
        [0.5904, 0.9335, 0.7379, 0.9741, 0.0167],
        [0.3658, 0.3736, 0.6770, 0.1896, 0.6115],
        [0.0708, 0.2734, 0.8226, 0.9077, 0.4072],
        [0.7364, 0.1484, 0.8783, 0.8323, 0.6857],
        [0.3176, 0.4852, 0.6456, 0.9907, 0.7190],
        [0.3763, 0.2832, 0.2025, 0.1559, 0.4693],
        [0.4051, 0.4113, 0.9593, 0.9061, 0.3148]])

In [31]:
features.shape

torch.Size([10, 5])

In [37]:
model = Model(features.shape[1])
# model.forward(features)
model(features)

tensor([[0.6132],
        [0.6135],
        [0.6162],
        [0.6203],
        [0.6210],
        [0.5981],
        [0.6272],
        [0.6259],
        [0.6209],
        [0.6096]], grad_fn=<SigmoidBackward0>)

In [40]:
model.linear1.weight

Parameter containing:
tensor([[-0.0944, -0.2981,  0.2659, -0.3955,  0.3621],
        [-0.4240, -0.3646,  0.0542, -0.2106, -0.0539],
        [ 0.0407, -0.0364, -0.0162, -0.2485,  0.2328]], requires_grad=True)

In [42]:
model.linear2.weight

Parameter containing:
tensor([[-0.4094, -0.4782,  0.1144]], requires_grad=True)

In [41]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [15]:
# Version 3


class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3), #index 0
        nn.ReLU() ,   #index 1
        nn.Linear(3,1),  #index 2
        nn.Sigmoid()  #index 3

    )

  def forward(self,features):
    out = self.network(features)

    return out

In [16]:
# Create dataset

features = torch.rand(10,5)

In [17]:
features

tensor([[0.0049, 0.8116, 0.9828, 0.1678, 0.3434],
        [0.0692, 0.0239, 0.0604, 0.4122, 0.7121],
        [0.4608, 0.4207, 0.6216, 0.9386, 0.2277],
        [0.9128, 0.5451, 0.9973, 0.2164, 0.0048],
        [0.8412, 0.8757, 0.8826, 0.3509, 0.1139],
        [0.9836, 0.3089, 0.7852, 0.2938, 0.8622],
        [0.2582, 0.2832, 0.1424, 0.1688, 0.3158],
        [0.3301, 0.2286, 0.1339, 0.1721, 0.4036],
        [0.6241, 0.0453, 0.1008, 0.2183, 0.8990],
        [0.0377, 0.8567, 0.0383, 0.7818, 0.4798]])

In [18]:
features.shape[1]

5

In [19]:
#create model

model = Model(features.shape[1])

In [20]:
#calling model for forward pass
# model.forward(features)

model(features)

tensor([[0.5846],
        [0.5616],
        [0.5722],
        [0.5799],
        [0.5822],
        [0.5936],
        [0.5680],
        [0.5693],
        [0.5799],
        [0.5543]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights

model.network[3].weight

AttributeError: 'Sigmoid' object has no attribute 'weight'

In [45]:
# Total number of trainable parameters
trainable_parameters = 0
for p in model.parameters():
  # print(p)
  if p.requires_grad:
    # print(p)
    # print(p.numel())
    trainable_parameters += p.numel()

print(trainable_parameters)

# total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
# print(total_params)

22


In [ ]:
# visualize

!pip install torchinfo

In [ ]:
from torchinfo import summary

summary( model,input_size = (10,5) )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Extra

In [ ]:
# Base Class
class Rectangle:
    def __init__(self, length, width):
        print("Rectangle constructor called")
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width


# Child Class (Square inherits Rectangle)
class Square(Rectangle):
    def __init__(self, side):
        print("Square constructor called")
        super().__init__(side, side)   # Calls Rectangle constructor

    def square_info(self):
        return f"Square area: {self.area()}"


# Child Class (Cube inherits Square)
class Cube(Square):
    def __init__(self, side):
        print("Cube constructor called")
        super().__init__(side)   # Calls Square constructor

    def volume(self):
        return self.length ** 3


# Create Object
cube = Cube(4)

print("Area:", cube.area())
print("Volume:", cube.volume())

In [2]:
class Test:
    def __call__(self, x):
        return x + 1

t = Test()
print(t(5))   # works like a function

6
